// Generated by tools/generate_abi65816.py; do not edit.
pub const ABI_NAME: &str = "action65816.native.v1";
pub const MANIFEST_FINGERPRINT: u64 = 0x4066ac26e5930a81;
pub const ABI_VERSION: u32 = 1;
pub const BOUNDARY_E: u32 = 0;
pub const BOUNDARY_P_M: u32 = 0;
pub const BOUNDARY_P_X: u32 = 0;
pub const BOUNDARY_P_D: u32 = 0;
pub const BOUNDARY_DBR: u32 = 0;
pub const BOUNDARY_ENTRY_S_MODULO_2: u32 = 0;
pub const BOUNDARY_BODY_S_MODULO_2: u32 = 0;
pub const BOUNDARY_BEFORE_CALL_S_MODULO_2: u32 = 1;
pub const CALL_MINIMUM_OUTGOING_BYTES: u32 = 1;
pub const CALL_PADDING_BYTE: u32 = 0;
pub const CALL_RETURN_ADDRESS_BYTES: u32 = 3;
pub const CALL_ENTRY_RETURN_PC_OFFSET: u32 = 1;
pub const CALL_ENTRY_RETURN_PBR_OFFSET: u32 = 3;
pub const CALL_ENTRY_FIRST_ARGUMENT_OFFSET: u32 = 4;
pub const CALL_DIRECT_TRANSFER_PEAK_BYTES: u32 = 3;
pub const CALL_INDIRECT_TRANSFER_PEAK_BYTES: u32 = 6;
pub const FRAME_BANK: u32 = 0;
pub const FRAME_FIXED_EXTENT_MULTIPLE: u32 = 2;
pub const FRAME_INITIAL_STRATEGY_MAX_FIXED_EXTENT: u32 = 254;
pub const FRAME_STACK_RELATIVE_MIN_DISPLACEMENT: u32 = 1;
pub const FRAME_STACK_RELATIVE_MAX_LAST_BYTE_DISPLACEMENT: u32 = 255;
pub const FRAME_MANDATORY_SAVED_REGISTER_BYTES: u32 = 0;
pub const FRAME_RED_ZONE_BYTES: u32 = 0;
pub const DP_BANK: u32 = 0;
pub const DP_SIZE: u32 = 256;
pub const DP_ALIGNMENT: u32 = 256;
pub const DP_SCRATCH_OFFSET: u32 = 0;
pub const DP_SCRATCH_SIZE: u32 = 64;
pub const DP_OWNER_POINTER_OFFSET: u32 = 64;
pub const DP_OWNER_POINTER_SIZE: u32 = 3;
pub const DP_DOMAIN_KIND_OFFSET: u32 = 67;
pub const DP_DOMAIN_KIND_SIZE: u32 = 1;
pub const DP_STACK_FLOOR_OFFSET: u32 = 68;
pub const DP_STACK_FLOOR_SIZE: u32 = 2;
pub const DP_STACK_CEILING_OFFSET: u32 = 70;
pub const DP_STACK_CEILING_SIZE: u32 = 2;
pub const DP_RESERVED_ZERO_OFFSET: u32 = 72;
pub const DP_RESERVED_ZERO_SIZE: u32 = 184;
pub const SAVED_FRAME_BANK: u32 = 0;
pub const SAVED_FRAME_SIZE: u32 = 13;
pub const SAVED_FRAME_FIRST_BYTE_OFFSET: u32 = 1;
pub const SAVED_FRAME_HARDWARE_BYTES: u32 = 4;
pub const SAVED_FRAME_SOFTWARE_BYTES: u32 = 9;
pub const SAVED_FRAME_ORIGINAL_S_DELTA: u32 = 13;
pub const SAVED_FRAME_DBR_OFFSET: u32 = 1;
pub const SAVED_FRAME_DBR_SIZE: u32 = 1;
pub const SAVED_FRAME_D_OFFSET: u32 = 2;
pub const SAVED_FRAME_D_SIZE: u32 = 2;
pub const SAVED_FRAME_Y_OFFSET: u32 = 4;
pub const SAVED_FRAME_Y_SIZE: u32 = 2;
pub const SAVED_FRAME_X_OFFSET: u32 = 6;
pub const SAVED_FRAME_X_SIZE: u32 = 2;
pub const SAVED_FRAME_A_FULL_OFFSET: u32 = 8;
pub const SAVED_FRAME_A_FULL_SIZE: u32 = 2;
pub const SAVED_FRAME_P_OFFSET: u32 = 10;
pub const SAVED_FRAME_P_SIZE: u32 = 1;
pub const SAVED_FRAME_PC_OFFSET: u32 = 11;
pub const SAVED_FRAME_PC_SIZE: u32 = 2;
pub const SAVED_FRAME_PBR_OFFSET: u32 = 13;
pub const SAVED_FRAME_PBR_SIZE: u32 = 1;
pub const CONTEXT_RECORD_SIZE: u32 = 2;
pub const CONTEXT_RECORD_ALIGNMENT: u32 = 2;
pub const CONTEXT_RECORD_SAVED_S_OFFSET: u32 = 0;
pub const CONTEXT_RECORD_SAVED_S_SIZE: u32 = 2;
pub const INTERRUPT_MAXIMUM_ACTIVE_IRQ_DISPATCHERS: u32 = 1;
pub const INTERRUPT_MAXIMUM_ACTIVE_NMI_HANDLERS: u32 = 1;
pub const INTERRUPT_TASK_OR_BOOTSTRAP_HEADROOM_BASE_BYTES: u32 = 26;
pub const INTERRUPT_IRQ_HEADROOM_BASE_BYTES: u32 = 13;
pub const INTERRUPT_YIELD_COP_SIGNATURE: u32 = 0;
pub const FIRST_TASK_EMPTY_BODY_S_MODULO_2: u32 = 0;
pub const FIRST_TASK_OUTGOING_BYTES: u32 = 3;
pub const FIRST_TASK_SAVED_S_BELOW_EMPTY_BODY_S: u32 = 19;
pub const FIRST_TASK_RETURN_PC_OFFSET_FROM_SAVED_S: u32 = 14;
pub const FIRST_TASK_RETURN_PBR_OFFSET_FROM_SAVED_S: u32 = 16;
pub const FIRST_TASK_ARGUMENT_OFFSET_FROM_SAVED_S: u32 = 17;
pub const FIRST_TASK_INITIAL_A: u32 = 0;
pub const FIRST_TASK_INITIAL_X: u32 = 0;
pub const FIRST_TASK_INITIAL_Y: u32 = 0;
pub const FIRST_TASK_INITIAL_DBR: u32 = 0;
pub const FIRST_TASK_IRQ_ENABLED_INITIAL_P: u32 = 0;
pub const FIRST_TASK_IRQ_DISABLED_INITIAL_P: u32 = 4;
pub const SCALAR_BYTE_SIZE: u32 = 1;
pub const SCALAR_BYTE_ALIGNMENT: u32 = 1;
pub const SCALAR_WORD_SIZE: u32 = 2;
pub const SCALAR_WORD_ALIGNMENT: u32 = 2;
pub const SCALAR_ADDRESS_OR_SIZE_SIZE: u32 = 3;
pub const SCALAR_ADDRESS_OR_SIZE_ALIGNMENT: u32 = 2;
pub const SCALAR_DATA_POINTER_SIZE: u32 = 3;
pub const SCALAR_DATA_POINTER_ALIGNMENT: u32 = 1;
pub const SCALAR_CODE_POINTER_SIZE: u32 = 3;
pub const SCALAR_CODE_POINTER_ALIGNMENT: u32 = 1;
pub const SCALAR_LONG_INTEGER_SIZE: u32 = 4;
pub const SCALAR_LONG_INTEGER_ALIGNMENT: u32 = 2;
pub const DOMAIN_TASK: u32 = 0;
pub const DOMAIN_IRQ: u32 = 1;
pub const DOMAIN_BOOTSTRAP: u32 = 2;
pub const DISPATCH_IRQ: u32 = 0;
pub const DISPATCH_YIELD: u32 = 1;
pub const DP_POINTER0_OFFSET: u32 = 0;
pub const DP_POINTER0_SIZE: u32 = 3;
pub const DP_POINTER1_OFFSET: u32 = 3;
pub const DP_POINTER1_SIZE: u32 = 3;
pub const DP_POINTER2_OFFSET: u32 = 6;
pub const DP_POINTER2_SIZE: u32 = 3;
pub const IRQ_TOKEN_ENABLED: u32 = 0;
pub const IRQ_TOKEN_DISABLED: u32 = 4;

#[cfg(test)]
#[rustfmt::skip]
pub(super) const MANIFEST_VALUES: &[(&str, &str, u32)] = &[
    ("/abi_version", "A816_ABI_VERSION", ABI_VERSION),
    ("/boundary/e", "A816_BOUNDARY_E", BOUNDARY_E),
    ("/boundary/p_m", "A816_BOUNDARY_P_M", BOUNDARY_P_M),
    ("/boundary/p_x", "A816_BOUNDARY_P_X", BOUNDARY_P_X),
    ("/boundary/p_d", "A816_BOUNDARY_P_D", BOUNDARY_P_D),
    ("/boundary/dbr", "A816_BOUNDARY_DBR", BOUNDARY_DBR),
    ("/boundary/entry_s_modulo_2", "A816_BOUNDARY_ENTRY_S_MODULO_2", BOUNDARY_ENTRY_S_MODULO_2),
    ("/boundary/body_s_modulo_2", "A816_BOUNDARY_BODY_S_MODULO_2", BOUNDARY_BODY_S_MODULO_2),
    ("/boundary/before_call_s_modulo_2", "A816_BOUNDARY_BEFORE_CALL_S_MODULO_2", BOUNDARY_BEFORE_CALL_S_MODULO_2),
    ("/calls/minimum_outgoing_bytes", "A816_CALL_MINIMUM_OUTGOING_BYTES", CALL_MINIMUM_OUTGOING_BYTES),
    ("/calls/padding_byte", "A816_CALL_PADDING_BYTE", CALL_PADDING_BYTE),
    ("/calls/return_address_bytes", "A816_CALL_RETURN_ADDRESS_BYTES", CALL_RETURN_ADDRESS_BYTES),
    ("/calls/entry_return_pc_offset", "A816_CALL_ENTRY_RETURN_PC_OFFSET", CALL_ENTRY_RETURN_PC_OFFSET),
    ("/calls/entry_return_pbr_offset", "A816_CALL_ENTRY_RETURN_PBR_OFFSET", CALL_ENTRY_RETURN_PBR_OFFSET),
    ("/calls/entry_first_argument_offset", "A816_CALL_ENTRY_FIRST_ARGUMENT_OFFSET", CALL_ENTRY_FIRST_ARGUMENT_OFFSET),
    ("/calls/direct_transfer_peak_bytes", "A816_CALL_DIRECT_TRANSFER_PEAK_BYTES", CALL_DIRECT_TRANSFER_PEAK_BYTES),
    ("/calls/indirect_transfer_peak_bytes", "A816_CALL_INDIRECT_TRANSFER_PEAK_BYTES", CALL_INDIRECT_TRANSFER_PEAK_BYTES),
    ("/frames/bank", "A816_FRAME_BANK", FRAME_BANK),
    ("/frames/fixed_extent_multiple", "A816_FRAME_FIXED_EXTENT_MULTIPLE", FRAME_FIXED_EXTENT_MULTIPLE),
    ("/frames/initial_strategy_max_fixed_extent", "A816_FRAME_INITIAL_STRATEGY_MAX_FIXED_EXTENT", FRAME_INITIAL_STRATEGY_MAX_FIXED_EXTENT),
    ("/frames/stack_relative_min_displacement", "A816_FRAME_STACK_RELATIVE_MIN_DISPLACEMENT", FRAME_STACK_RELATIVE_MIN_DISPLACEMENT),
    ("/frames/stack_relative_max_last_byte_displacement", "A816_FRAME_STACK_RELATIVE_MAX_LAST_BYTE_DISPLACEMENT", FRAME_STACK_RELATIVE_MAX_LAST_BYTE_DISPLACEMENT),
    ("/frames/mandatory_saved_register_bytes", "A816_FRAME_MANDATORY_SAVED_REGISTER_BYTES", FRAME_MANDATORY_SAVED_REGISTER_BYTES),
    ("/frames/red_zone_bytes", "A816_FRAME_RED_ZONE_BYTES", FRAME_RED_ZONE_BYTES),
    ("/direct_page/bank", "A816_DP_BANK", DP_BANK),
    ("/direct_page/size", "A816_DP_SIZE", DP_SIZE),
    ("/direct_page/alignment", "A816_DP_ALIGNMENT", DP_ALIGNMENT),
    ("/direct_page/fields/0/offset", "A816_DP_SCRATCH_OFFSET", DP_SCRATCH_OFFSET),
    ("/direct_page/fields/0/size", "A816_DP_SCRATCH_SIZE", DP_SCRATCH_SIZE),
    ("/direct_page/fields/1/offset", "A816_DP_OWNER_POINTER_OFFSET", DP_OWNER_POINTER_OFFSET),
    ("/direct_page/fields/1/size", "A816_DP_OWNER_POINTER_SIZE", DP_OWNER_POINTER_SIZE),
    ("/direct_page/fields/2/offset", "A816_DP_DOMAIN_KIND_OFFSET", DP_DOMAIN_KIND_OFFSET),
    ("/direct_page/fields/2/size", "A816_DP_DOMAIN_KIND_SIZE", DP_DOMAIN_KIND_SIZE),
    ("/direct_page/fields/3/offset", "A816_DP_STACK_FLOOR_OFFSET", DP_STACK_FLOOR_OFFSET),
    ("/direct_page/fields/3/size", "A816_DP_STACK_FLOOR_SIZE", DP_STACK_FLOOR_SIZE),
    ("/direct_page/fields/4/offset", "A816_DP_STACK_CEILING_OFFSET", DP_STACK_CEILING_OFFSET),
    ("/direct_page/fields/4/size", "A816_DP_STACK_CEILING_SIZE", DP_STACK_CEILING_SIZE),
    ("/direct_page/fields/5/offset", "A816_DP_RESERVED_ZERO_OFFSET", DP_RESERVED_ZERO_OFFSET),
    ("/direct_page/fields/5/size", "A816_DP_RESERVED_ZERO_SIZE", DP_RESERVED_ZERO_SIZE),
    ("/saved_frame/bank", "A816_SAVED_FRAME_BANK", SAVED_FRAME_BANK),
    ("/saved_frame/size", "A816_SAVED_FRAME_SIZE", SAVED_FRAME_SIZE),
    ("/saved_frame/first_byte_offset", "A816_SAVED_FRAME_FIRST_BYTE_OFFSET", SAVED_FRAME_FIRST_BYTE_OFFSET),
    ("/saved_frame/hardware_bytes", "A816_SAVED_FRAME_HARDWARE_BYTES", SAVED_FRAME_HARDWARE_BYTES),
    ("/saved_frame/software_bytes", "A816_SAVED_FRAME_SOFTWARE_BYTES", SAVED_FRAME_SOFTWARE_BYTES),
    ("/saved_frame/original_s_delta", "A816_SAVED_FRAME_ORIGINAL_S_DELTA", SAVED_FRAME_ORIGINAL_S_DELTA),
    ("/saved_frame/fields/0/offset", "A816_SAVED_FRAME_DBR_OFFSET", SAVED_FRAME_DBR_OFFSET),
    ("/saved_frame/fields/0/size", "A816_SAVED_FRAME_DBR_SIZE", SAVED_FRAME_DBR_SIZE),
    ("/saved_frame/fields/1/offset", "A816_SAVED_FRAME_D_OFFSET", SAVED_FRAME_D_OFFSET),
    ("/saved_frame/fields/1/size", "A816_SAVED_FRAME_D_SIZE", SAVED_FRAME_D_SIZE),
    ("/saved_frame/fields/2/offset", "A816_SAVED_FRAME_Y_OFFSET", SAVED_FRAME_Y_OFFSET),
    ("/saved_frame/fields/2/size", "A816_SAVED_FRAME_Y_SIZE", SAVED_FRAME_Y_SIZE),
    ("/saved_frame/fields/3/offset", "A816_SAVED_FRAME_X_OFFSET", SAVED_FRAME_X_OFFSET),
    ("/saved_frame/fields/3/size", "A816_SAVED_FRAME_X_SIZE", SAVED_FRAME_X_SIZE),
    ("/saved_frame/fields/4/offset", "A816_SAVED_FRAME_A_FULL_OFFSET", SAVED_FRAME_A_FULL_OFFSET),
    ("/saved_frame/fields/4/size", "A816_SAVED_FRAME_A_FULL_SIZE", SAVED_FRAME_A_FULL_SIZE),
    ("/saved_frame/fields/5/offset", "A816_SAVED_FRAME_P_OFFSET", SAVED_FRAME_P_OFFSET),
    ("/saved_frame/fields/5/size", "A816_SAVED_FRAME_P_SIZE", SAVED_FRAME_P_SIZE),
    ("/saved_frame/fields/6/offset", "A816_SAVED_FRAME_PC_OFFSET", SAVED_FRAME_PC_OFFSET),
    ("/saved_frame/fields/6/size", "A816_SAVED_FRAME_PC_SIZE", SAVED_FRAME_PC_SIZE),
    ("/saved_frame/fields/7/offset", "A816_SAVED_FRAME_PBR_OFFSET", SAVED_FRAME_PBR_OFFSET),
    ("/saved_frame/fields/7/size", "A816_SAVED_FRAME_PBR_SIZE", SAVED_FRAME_PBR_SIZE),
    ("/context_record/size", "A816_CONTEXT_RECORD_SIZE", CONTEXT_RECORD_SIZE),
    ("/context_record/alignment", "A816_CONTEXT_RECORD_ALIGNMENT", CONTEXT_RECORD_ALIGNMENT),
    ("/context_record/fields/0/offset", "A816_CONTEXT_RECORD_SAVED_S_OFFSET", CONTEXT_RECORD_SAVED_S_OFFSET),
    ("/context_record/fields/0/size", "A816_CONTEXT_RECORD_SAVED_S_SIZE", CONTEXT_RECORD_SAVED_S_SIZE),
    ("/interrupts/maximum_active_irq_dispatchers", "A816_INTERRUPT_MAXIMUM_ACTIVE_IRQ_DISPATCHERS", INTERRUPT_MAXIMUM_ACTIVE_IRQ_DISPATCHERS),
    ("/interrupts/maximum_active_nmi_handlers", "A816_INTERRUPT_MAXIMUM_ACTIVE_NMI_HANDLERS", INTERRUPT_MAXIMUM_ACTIVE_NMI_HANDLERS),
    ("/interrupts/task_or_bootstrap_headroom_base_bytes", "A816_INTERRUPT_TASK_OR_BOOTSTRAP_HEADROOM_BASE_BYTES", INTERRUPT_TASK_OR_BOOTSTRAP_HEADROOM_BASE_BYTES),
    ("/interrupts/irq_headroom_base_bytes", "A816_INTERRUPT_IRQ_HEADROOM_BASE_BYTES", INTERRUPT_IRQ_HEADROOM_BASE_BYTES),
    ("/interrupts/yield_cop_signature", "A816_INTERRUPT_YIELD_COP_SIGNATURE", INTERRUPT_YIELD_COP_SIGNATURE),
    ("/first_task/empty_body_s_modulo_2", "A816_FIRST_TASK_EMPTY_BODY_S_MODULO_2", FIRST_TASK_EMPTY_BODY_S_MODULO_2),
    ("/first_task/outgoing_bytes", "A816_FIRST_TASK_OUTGOING_BYTES", FIRST_TASK_OUTGOING_BYTES),
    ("/first_task/saved_s_below_empty_body_s", "A816_FIRST_TASK_SAVED_S_BELOW_EMPTY_BODY_S", FIRST_TASK_SAVED_S_BELOW_EMPTY_BODY_S),
    ("/first_task/return_pc_offset_from_saved_s", "A816_FIRST_TASK_RETURN_PC_OFFSET_FROM_SAVED_S", FIRST_TASK_RETURN_PC_OFFSET_FROM_SAVED_S),
    ("/first_task/return_pbr_offset_from_saved_s", "A816_FIRST_TASK_RETURN_PBR_OFFSET_FROM_SAVED_S", FIRST_TASK_RETURN_PBR_OFFSET_FROM_SAVED_S),
    ("/first_task/argument_offset_from_saved_s", "A816_FIRST_TASK_ARGUMENT_OFFSET_FROM_SAVED_S", FIRST_TASK_ARGUMENT_OFFSET_FROM_SAVED_S),
    ("/first_task/initial_a", "A816_FIRST_TASK_INITIAL_A", FIRST_TASK_INITIAL_A),
    ("/first_task/initial_x", "A816_FIRST_TASK_INITIAL_X", FIRST_TASK_INITIAL_X),
    ("/first_task/initial_y", "A816_FIRST_TASK_INITIAL_Y", FIRST_TASK_INITIAL_Y),
    ("/first_task/initial_dbr", "A816_FIRST_TASK_INITIAL_DBR", FIRST_TASK_INITIAL_DBR),
    ("/first_task/irq_enabled_initial_p", "A816_FIRST_TASK_IRQ_ENABLED_INITIAL_P", FIRST_TASK_IRQ_ENABLED_INITIAL_P),
    ("/first_task/irq_disabled_initial_p", "A816_FIRST_TASK_IRQ_DISABLED_INITIAL_P", FIRST_TASK_IRQ_DISABLED_INITIAL_P),
    ("/scalar_classes/byte/size", "A816_SCALAR_BYTE_SIZE", SCALAR_BYTE_SIZE),
    ("/scalar_classes/byte/alignment", "A816_SCALAR_BYTE_ALIGNMENT", SCALAR_BYTE_ALIGNMENT),
    ("/scalar_classes/word/size", "A816_SCALAR_WORD_SIZE", SCALAR_WORD_SIZE),
    ("/scalar_classes/word/alignment", "A816_SCALAR_WORD_ALIGNMENT", SCALAR_WORD_ALIGNMENT),
    ("/scalar_classes/address_or_size/size", "A816_SCALAR_ADDRESS_OR_SIZE_SIZE", SCALAR_ADDRESS_OR_SIZE_SIZE),
    ("/scalar_classes/address_or_size/alignment", "A816_SCALAR_ADDRESS_OR_SIZE_ALIGNMENT", SCALAR_ADDRESS_OR_SIZE_ALIGNMENT),
    ("/scalar_classes/data_pointer/size", "A816_SCALAR_DATA_POINTER_SIZE", SCALAR_DATA_POINTER_SIZE),
    ("/scalar_classes/data_pointer/alignment", "A816_SCALAR_DATA_POINTER_ALIGNMENT", SCALAR_DATA_POINTER_ALIGNMENT),
    ("/scalar_classes/code_pointer/size", "A816_SCALAR_CODE_POINTER_SIZE", SCALAR_CODE_POINTER_SIZE),
    ("/scalar_classes/code_pointer/alignment", "A816_SCALAR_CODE_POINTER_ALIGNMENT", SCALAR_CODE_POINTER_ALIGNMENT),
    ("/scalar_classes/long_integer/size", "A816_SCALAR_LONG_INTEGER_SIZE", SCALAR_LONG_INTEGER_SIZE),
    ("/scalar_classes/long_integer/alignment", "A816_SCALAR_LONG_INTEGER_ALIGNMENT", SCALAR_LONG_INTEGER_ALIGNMENT),
    ("/direct_page/domain_kinds/task", "A816_DOMAIN_TASK", DOMAIN_TASK),
    ("/direct_page/domain_kinds/irq", "A816_DOMAIN_IRQ", DOMAIN_IRQ),
    ("/direct_page/domain_kinds/bootstrap", "A816_DOMAIN_BOOTSTRAP", DOMAIN_BOOTSTRAP),
    ("/interrupts/dispatch_reasons/irq", "A816_DISPATCH_IRQ", DISPATCH_IRQ),
    ("/interrupts/dispatch_reasons/yield", "A816_DISPATCH_YIELD", DISPATCH_YIELD),
    ("/direct_page/scratch_aliases/0/offset", "A816_DP_POINTER0_OFFSET", DP_POINTER0_OFFSET),
    ("/direct_page/scratch_aliases/0/size", "A816_DP_POINTER0_SIZE", DP_POINTER0_SIZE),
    ("/direct_page/scratch_aliases/1/offset", "A816_DP_POINTER1_OFFSET", DP_POINTER1_OFFSET),
    ("/direct_page/scratch_aliases/1/size", "A816_DP_POINTER1_SIZE", DP_POINTER1_SIZE),
    ("/direct_page/scratch_aliases/2/offset", "A816_DP_POINTER2_OFFSET", DP_POINTER2_OFFSET),
    ("/direct_page/scratch_aliases/2/size", "A816_DP_POINTER2_SIZE", DP_POINTER2_SIZE),
    ("/irq_state_tokens/enabled", "A816_IRQ_TOKEN_ENABLED", IRQ_TOKEN_ENABLED),
    ("/irq_state_tokens/disabled", "A816_IRQ_TOKEN_DISABLED", IRQ_TOKEN_DISABLED),
];
