use std::collections::{BTreeMap, BTreeSet};

use crate::codegen::{
    AddressingMode, CodegenOutput, CodegenSourceRangeKind, CodegenSymbolKind, CodegenSymbolScope,
    DisassembledInstruction, disassemble_with_origin_and_inline_jsr_data,
};
use crate::map_query::MapQuery;

pub(crate) fn format_listing_with_source(output: &CodegenOutput, source_text: &str) -> String {
    format_mads_listing(output, Some(source_text))
}

pub(crate) fn format_listing_with_boundaries(output: &CodegenOutput) -> String {
    format_mads_listing(output, None)
}

fn format_mads_listing(output: &CodegenOutput, source_text: Option<&str>) -> String {
    let boundary_comments = routine_boundary_comments(output);
    let instructions = disassemble_code_ranges(output);
    let items = listing_items(output, &instructions);
    let display_symbols = MadsDisplaySymbols::from_output(output, &instructions, &items);
    let routine_labels = routine_address_labels(output);
    let query = source_text.map(|source| MapQuery::with_source(&output.map, source));
    let mut last_source = None;
    let mut lines = vec![
        "; Generated by actionc. Fixed-origin MADS assembly listing.".to_string(),
        "; Reassembly is expected to reproduce the unedited actionc load file.".to_string(),
        String::new(),
        format!("        ORG ${:04X}", output.origin),
        String::new(),
    ];
    display_symbols.push_equates(&mut lines);

    for item in items {
        match item {
            ListingItem::Instruction(instruction) => {
                if let Some(comments) = boundary_comments.get(&instruction.address) {
                    push_assembly_comments(&mut lines, comments);
                }
                display_symbols.push_definitions(instruction.address, &mut lines);
                if let Some(query) = &query {
                    push_source_comment(query, instruction.address, &mut last_source, &mut lines);
                }
                lines.push(format_instruction_listing(
                    &instruction,
                    &display_symbols,
                    &routine_labels,
                ));
            }
            ListingItem::Data {
                address,
                bytes,
                name,
            } => {
                if let Some(comments) = boundary_comments.get(&address) {
                    push_assembly_comments(&mut lines, comments);
                }
                display_symbols.push_definitions(address, &mut lines);
                if let Some(query) = &query {
                    push_source_comment(query, address, &mut last_source, &mut lines);
                }
                if let Some(name) = name {
                    lines.push(sanitize_assembly_comment(&format!(
                        "; ===== DATA {name} ${address:04X} ====="
                    )));
                }
                lines.push(format_data_listing(address, &bytes));
            }
        }
    }

    append_trailing_boundary_comments(output, &boundary_comments, &mut lines);
    lines.push(String::new());
    lines.push("; Atari RUNAD segment.".to_string());
    lines.push("        ORG $02E2".to_string());
    let run_address = display_symbols
        .code_reference(output.run_address)
        .map(str::to_string)
        .unwrap_or_else(|| format!("${:04X}", output.run_address));
    lines.push(format!("        DTA A({run_address})"));
    lines.join("\n")
}

#[derive(Debug, Default)]
struct MadsDisplaySymbols {
    code_references: BTreeMap<u16, String>,
    global_storage_references: BTreeMap<u16, String>,
    routine_storage_references: BTreeMap<(String, u16), String>,
    routine_ranges: Vec<(u16, u16, String)>,
    definitions: BTreeMap<u16, Vec<String>>,
    equates: Vec<(String, u16)>,
}

impl MadsDisplaySymbols {
    fn from_output(
        output: &CodegenOutput,
        instructions: &[DisassembledInstruction],
        items: &[ListingItem],
    ) -> Self {
        let item_addresses = items
            .iter()
            .map(ListingItem::address)
            .collect::<BTreeSet<_>>();
        let mut used_names = BTreeSet::new();
        let mut symbols = Self {
            routine_ranges: output
                .map
                .routine_ranges
                .iter()
                .map(|range| (range.start, range.end, range.name.to_ascii_lowercase()))
                .collect(),
            ..Self::default()
        };

        let mut routines = output.map.routine_addresses.iter().collect::<Vec<_>>();
        routines.sort_by(|left, right| {
            left.address
                .cmp(&right.address)
                .then_with(|| left.name.cmp(&right.name))
        });
        for routine in routines {
            if is_pseudo_routine_name(&routine.name) {
                continue;
            }
            let base = format!("proc_{}", sanitize_mads_component(&routine.name));
            let name = allocate_mads_symbol(&base, &mut used_names);
            symbols
                .code_references
                .entry(routine.address)
                .or_insert_with(|| name.clone());
            symbols.add_semantic_symbol(name, routine.address, &item_addresses);
        }

        let mut storage = output.map.storage_symbols.iter().collect::<Vec<_>>();
        storage.sort_by(|left, right| {
            left.address
                .cmp(&right.address)
                .then_with(|| storage_symbol_base(left).cmp(&storage_symbol_base(right)))
        });
        for symbol in storage {
            let base = storage_symbol_base(symbol);
            let name = allocate_mads_symbol(&base, &mut used_names);
            match &symbol.scope {
                CodegenSymbolScope::Global => {
                    symbols
                        .global_storage_references
                        .entry(symbol.address)
                        .or_insert_with(|| name.clone());
                }
                CodegenSymbolScope::Routine(routine) => {
                    symbols
                        .routine_storage_references
                        .entry((routine.to_ascii_lowercase(), symbol.address))
                        .or_insert_with(|| name.clone());
                }
            }
            symbols.add_semantic_symbol(name, symbol.address, &item_addresses);
        }

        let instruction_addresses = instructions
            .iter()
            .map(|instruction| instruction.address)
            .collect::<BTreeSet<_>>();
        for instruction in instructions {
            let Some(target) = instruction_target(instruction) else {
                continue;
            };
            if !instruction_addresses.contains(&target) {
                continue;
            }
            if symbols.code_references.contains_key(&target) {
                continue;
            }
            let name = format!("L{target:04X}");
            used_names.insert(name.to_ascii_lowercase());
            symbols.code_references.insert(target, name.clone());
            symbols.definitions.entry(target).or_default().push(name);
        }

        for definitions in symbols.definitions.values_mut() {
            definitions.sort();
            definitions.dedup();
        }
        symbols
            .equates
            .sort_by(|left, right| left.1.cmp(&right.1).then_with(|| left.0.cmp(&right.0)));
        symbols
    }

    fn add_semantic_symbol(&mut self, name: String, address: u16, item_addresses: &BTreeSet<u16>) {
        if item_addresses.contains(&address) {
            self.definitions.entry(address).or_default().push(name);
        } else {
            self.equates.push((name, address));
        }
    }

    fn push_equates(&self, lines: &mut Vec<String>) {
        if self.equates.is_empty() {
            return;
        }
        lines.push("; Semantic symbols outside emitted item boundaries.".to_string());
        lines.extend(
            self.equates
                .iter()
                .map(|(name, address)| format!("{name} = ${address:04X}")),
        );
        lines.push(String::new());
    }

    fn push_definitions(&self, address: u16, lines: &mut Vec<String>) {
        if let Some(definitions) = self.definitions.get(&address) {
            lines.extend(definitions.iter().map(|name| format!("{name}:")));
        }
    }

    fn code_reference(&self, address: u16) -> Option<&str> {
        self.code_references.get(&address).map(String::as_str)
    }

    fn storage_reference(&self, address: u16, instruction_address: u16) -> Option<&str> {
        self.routine_ranges
            .iter()
            .filter(|(start, end, _)| instruction_address >= *start && instruction_address < *end)
            .find_map(|(_, _, routine)| {
                self.routine_storage_references
                    .get(&(routine.clone(), address))
            })
            .or_else(|| self.global_storage_references.get(&address))
            .map(String::as_str)
    }
}

impl ListingItem {
    fn address(&self) -> u16 {
        match self {
            Self::Instruction(instruction) => instruction.address,
            Self::Data { address, .. } => *address,
        }
    }
}

fn is_pseudo_routine_name(name: &str) -> bool {
    name.starts_with('<') && name.ends_with('>')
}

fn storage_symbol_base(symbol: &crate::codegen::CodegenStorageSymbol) -> String {
    let name = sanitize_mads_component(&symbol.name);
    match &symbol.scope {
        CodegenSymbolScope::Global => {
            if let Some(static_name) = symbol.name.strip_prefix("__nir_str_") {
                format!("static_string_{}", sanitize_mads_component(static_name))
            } else {
                format!("global_{name}")
            }
        }
        CodegenSymbolScope::Routine(routine) => {
            let routine = sanitize_mads_component(routine);
            match symbol.kind {
                CodegenSymbolKind::Parameter => format!("param_{routine}_{name}"),
                CodegenSymbolKind::Local if name.starts_with("spill") => {
                    format!("spill_{routine}_{}", name.trim_start_matches("spill"))
                }
                CodegenSymbolKind::Local => format!("local_{routine}_{name}"),
                CodegenSymbolKind::Storage => format!("storage_{routine}_{name}"),
            }
        }
    }
}

fn sanitize_mads_component(value: &str) -> String {
    let mut sanitized = String::new();
    let mut previous_was_separator = false;
    for character in value.chars() {
        if character.is_ascii_alphanumeric() || character == '_' {
            sanitized.push(character.to_ascii_lowercase());
            previous_was_separator = false;
        } else if !previous_was_separator {
            sanitized.push('_');
            previous_was_separator = true;
        }
    }
    let sanitized = sanitized.trim_matches('_');
    if sanitized.is_empty() {
        "unnamed".to_string()
    } else {
        sanitized.to_string()
    }
}

fn allocate_mads_symbol(base: &str, used_names: &mut BTreeSet<String>) -> String {
    let normalized = base.to_ascii_lowercase();
    if used_names.insert(normalized) {
        return base.to_string();
    }
    for suffix in 2usize.. {
        let candidate = format!("{base}__{suffix}");
        if used_names.insert(candidate.to_ascii_lowercase()) {
            return candidate;
        }
    }
    unreachable!("MADS display-symbol suffix space is unbounded")
}

#[derive(Debug, Clone)]
enum ListingItem {
    Instruction(DisassembledInstruction),
    Data {
        address: u16,
        bytes: Vec<u8>,
        name: Option<String>,
    },
}

fn listing_items(
    output: &CodegenOutput,
    instructions: &[DisassembledInstruction],
) -> Vec<ListingItem> {
    let mut items = Vec::new();
    let mut instruction_index = 0;
    let mut cursor = output.origin;
    let end = output
        .origin
        .wrapping_add(u16::try_from(output.bytes.len()).unwrap_or(u16::MAX));
    let storage = storage_listing_ranges(output);
    let mut storage_index = 0;

    while cursor < end {
        if let Some(symbol) = storage.get(storage_index)
            && symbol.address == cursor
        {
            for (chunk_index, chunk) in symbol.bytes.chunks(8).enumerate() {
                items.push(ListingItem::Data {
                    address: symbol.address.saturating_add((chunk_index * 8) as u16),
                    bytes: chunk.to_vec(),
                    name: (chunk_index == 0).then(|| symbol.name.clone()),
                });
            }
            cursor = symbol.address.saturating_add(symbol.bytes.len() as u16);
            storage_index += 1;
            continue;
        }

        while let Some(instruction) = instructions.get(instruction_index)
            && instruction.address < cursor
        {
            instruction_index += 1;
        }

        if let Some(instruction) = instructions.get(instruction_index)
            && instruction.address == cursor
        {
            items.push(ListingItem::Instruction(instruction.clone()));
            cursor = cursor.saturating_add(instruction.bytes.len() as u16);
            instruction_index += 1;
            continue;
        }

        let Some(offset) = output_offset(output, cursor) else {
            break;
        };
        items.push(ListingItem::Data {
            address: cursor,
            bytes: vec![output.bytes[offset]],
            name: None,
        });
        cursor = cursor.saturating_add(1);
    }

    items
}

#[derive(Debug, Clone)]
struct StorageListingRange {
    address: u16,
    bytes: Vec<u8>,
    name: String,
}

fn storage_listing_ranges(output: &CodegenOutput) -> Vec<StorageListingRange> {
    let mut ranges = output
        .map
        .storage_symbols
        .iter()
        .filter(|symbol| !address_in_routine(output, symbol.address))
        .filter_map(|symbol| {
            let start = output_offset(output, symbol.address)?;
            let end = start.saturating_add(symbol.size as usize);
            let bytes = output.bytes.get(start..end)?.to_vec();
            Some(StorageListingRange {
                address: symbol.address,
                bytes,
                name: symbol.name.clone(),
            })
        })
        .collect::<Vec<_>>();
    ranges.extend(storage_source_listing_ranges(output));
    ranges.sort_by_key(|range| range.address);
    ranges.dedup_by_key(|range| range.address);
    ranges
}

fn storage_source_listing_ranges(output: &CodegenOutput) -> Vec<StorageListingRange> {
    output
        .map
        .source_ranges
        .iter()
        .filter(|range| range.kind == CodegenSourceRangeKind::StorageInitializer)
        .filter_map(|range| {
            let start = output_offset(output, range.start)?;
            let end = output_end_offset(output, range.end)?;
            let bytes = output.bytes.get(start..end)?.to_vec();
            (!bytes.is_empty()).then(|| StorageListingRange {
                address: range.start,
                bytes,
                name: range.name.clone().unwrap_or_else(|| "storage".to_string()),
            })
        })
        .collect()
}

fn disassemble_code_ranges(output: &CodegenOutput) -> Vec<DisassembledInstruction> {
    let mut ranges = output.map.routine_ranges.clone();
    ranges.sort_by_key(|range| range.start);
    let mut storage = storage_source_listing_ranges(output);
    storage.sort_by_key(|range| range.address);
    let inline_jsr_data_lengths = inline_jsr_data_lengths(output);
    let mut instructions = Vec::new();
    for range in ranges {
        let mut cursor = range.start;
        for data in storage.iter().filter(|data| {
            let data_end = data.address.saturating_add(data.bytes.len() as u16);
            data.address < range.end && data_end > range.start
        }) {
            if data.address > cursor {
                push_disassembled_range(
                    output,
                    cursor,
                    data.address,
                    &inline_jsr_data_lengths,
                    &mut instructions,
                );
            }
            cursor = cursor.max(data.address.saturating_add(data.bytes.len() as u16));
        }
        if cursor < range.end {
            push_disassembled_range(
                output,
                cursor,
                range.end,
                &inline_jsr_data_lengths,
                &mut instructions,
            );
        }
    }
    instructions
}

fn push_disassembled_range(
    output: &CodegenOutput,
    start_address: u16,
    end_address: u16,
    inline_jsr_data_lengths: &BTreeMap<u16, usize>,
    instructions: &mut Vec<DisassembledInstruction>,
) {
    if end_address <= start_address {
        return;
    }
    let Some(start) = output_offset(output, start_address) else {
        return;
    };
    let Some(end) = output_end_offset(output, end_address) else {
        return;
    };
    instructions.extend(disassemble_with_origin_and_inline_jsr_data(
        output.bytes.get(start..end).unwrap_or_default(),
        start_address,
        |target| inline_jsr_data_lengths.get(&target).copied(),
    ));
}

fn inline_jsr_data_lengths(output: &CodegenOutput) -> BTreeMap<u16, usize> {
    output
        .map
        .routine_addresses
        .iter()
        // Action! r_Par consumes three inline parameter bytes after the JSR.
        .filter(|routine| routine.name.eq_ignore_ascii_case("r_Par"))
        .map(|routine| (routine.address, 3))
        .collect()
}

fn address_in_routine(output: &CodegenOutput, address: u16) -> bool {
    output
        .map
        .routine_ranges
        .iter()
        .any(|range| address >= range.start && address < range.end)
}

fn output_offset(output: &CodegenOutput, address: u16) -> Option<usize> {
    if address < output.origin {
        return None;
    }
    let offset = address.wrapping_sub(output.origin) as usize;
    (offset < output.bytes.len()).then_some(offset)
}

fn output_end_offset(output: &CodegenOutput, address: u16) -> Option<usize> {
    if address < output.origin {
        return None;
    }
    let offset = address.wrapping_sub(output.origin) as usize;
    (offset <= output.bytes.len()).then_some(offset)
}

fn push_source_comment(
    query: &MapQuery<'_>,
    address: u16,
    last_source: &mut Option<(usize, usize, u16, u16)>,
    lines: &mut Vec<String>,
) {
    let Some(source) = query.source_at(address) else {
        return;
    };
    let range = source.range;
    let key = (
        range.source_span.start,
        range.source_span.end,
        range.start,
        range.end,
    );
    if *last_source == Some(key) {
        return;
    }
    *last_source = Some(key);
    if let Some(location) = source.location {
        lines.push(sanitize_assembly_comment(&format!(
            "; {}:{} {}{} | {}",
            location.line,
            location.column,
            format_source_range_kind(range.kind),
            range
                .name
                .as_ref()
                .map(|name| format!(" {name}"))
                .unwrap_or_default(),
            location.excerpt
        )));
    }
}

fn format_instruction_listing(
    instruction: &DisassembledInstruction,
    display_symbols: &MadsDisplaySymbols,
    routine_labels: &BTreeMap<u16, String>,
) -> String {
    let assembly = format_mads_instruction(instruction, display_symbols);
    let annotation = if instruction.mnemonic == "JSR"
        && let Some(target) = le_u16_from_slice(&instruction.operands)
        && let Some(label) = routine_labels.get(&target)
    {
        Some(label.as_str())
    } else {
        None
    };
    format_assembly_line(
        &assembly,
        instruction.address,
        &instruction.bytes,
        annotation,
    )
}

fn format_data_listing(address: u16, bytes: &[u8]) -> String {
    format_assembly_line(&format_byte_directive(bytes), address, bytes, None)
}

fn format_mads_instruction(
    instruction: &DisassembledInstruction,
    display_symbols: &MadsDisplaySymbols,
) -> String {
    let Some(mode) = instruction.mode else {
        return format_byte_directive(&instruction.bytes);
    };
    let mnemonic = instruction.mnemonic;
    let byte = || {
        *instruction
            .operands
            .first()
            .expect("decoded byte operand must be present")
    };
    let word =
        || le_u16_from_slice(&instruction.operands).expect("decoded word operand must be present");

    match mode {
        AddressingMode::Implied | AddressingMode::Accumulator => mnemonic.to_string(),
        AddressingMode::Immediate => format!("{mnemonic} #${:02X}", byte()),
        AddressingMode::ZeroPage => format!(
            "{mnemonic}.Z {}",
            storage_operand(display_symbols, u16::from(byte()), instruction.address, 2,)
        ),
        AddressingMode::ZeroPageX => format!(
            "{mnemonic}.Z {},X",
            storage_operand(display_symbols, u16::from(byte()), instruction.address, 2,)
        ),
        AddressingMode::ZeroPageY => format!(
            "{mnemonic}.Z {},Y",
            storage_operand(display_symbols, u16::from(byte()), instruction.address, 2,)
        ),
        AddressingMode::Absolute => {
            let target = word();
            let operand = if matches!(mnemonic, "JMP" | "JSR") {
                display_symbols
                    .code_reference(target)
                    .map(str::to_string)
                    .unwrap_or_else(|| format!("${target:04X}"))
            } else {
                storage_operand(display_symbols, target, instruction.address, 4)
            };
            format!("{mnemonic}.A {operand}")
        }
        AddressingMode::AbsoluteX => format!(
            "{mnemonic}.A {},X",
            storage_operand(display_symbols, word(), instruction.address, 4)
        ),
        AddressingMode::AbsoluteY => format!(
            "{mnemonic}.A {},Y",
            storage_operand(display_symbols, word(), instruction.address, 4)
        ),
        AddressingMode::Indirect => format!(
            "{mnemonic} ({})",
            storage_operand(display_symbols, word(), instruction.address, 4)
        ),
        AddressingMode::IndexedIndirectX => format!(
            "{mnemonic} ({},X)",
            storage_operand(display_symbols, u16::from(byte()), instruction.address, 2,)
        ),
        AddressingMode::IndirectIndexedY => format!(
            "{mnemonic} ({}),Y",
            storage_operand(display_symbols, u16::from(byte()), instruction.address, 2,)
        ),
        AddressingMode::Relative => {
            let target = instruction
                .address
                .wrapping_add(2)
                .wrapping_add_signed(i16::from(byte() as i8));
            let operand = display_symbols
                .code_reference(target)
                .map(str::to_string)
                .unwrap_or_else(|| format!("${target:04X}"));
            format!("{mnemonic} {operand}")
        }
    }
}

fn storage_operand(
    symbols: &MadsDisplaySymbols,
    address: u16,
    instruction_address: u16,
    hex_width: usize,
) -> String {
    symbols
        .storage_reference(address, instruction_address)
        .map(str::to_string)
        .unwrap_or_else(|| format!("${address:0hex_width$X}"))
}

fn format_byte_directive(bytes: &[u8]) -> String {
    let values = bytes
        .iter()
        .map(|byte| format!("${byte:02X}"))
        .collect::<Vec<_>>()
        .join(",");
    format!(".BYTE {values}")
}

fn format_assembly_line(
    assembly: &str,
    address: u16,
    bytes: &[u8],
    annotation: Option<&str>,
) -> String {
    let raw = bytes
        .iter()
        .map(|byte| format!("{byte:02X}"))
        .collect::<Vec<_>>()
        .join(" ");
    let annotation = annotation
        .map(sanitize_comment_text)
        .map(|text| format!(" ; {text}"))
        .unwrap_or_default();
    format!("        {assembly:<36} ; ${address:04X}: {raw}{annotation}")
}

fn routine_address_labels(output: &CodegenOutput) -> BTreeMap<u16, String> {
    output
        .map
        .routine_addresses
        .iter()
        .map(|routine| (routine.address, routine.name.clone()))
        .collect()
}

fn instruction_target(item: &DisassembledInstruction) -> Option<u16> {
    match item.mode? {
        AddressingMode::Relative => {
            let offset = *item.operands.first()? as i8;
            Some(
                item.address
                    .wrapping_add(2)
                    .wrapping_add_signed(i16::from(offset)),
            )
        }
        AddressingMode::Absolute | AddressingMode::AbsoluteX => {
            if matches!(item.mnemonic, "JMP" | "JSR") {
                le_u16_from_slice(&item.operands)
            } else {
                None
            }
        }
        _ => None,
    }
}

fn le_u16_from_slice(bytes: &[u8]) -> Option<u16> {
    Some(u16::from(*bytes.first()?) | (u16::from(*bytes.get(1)?) << 8))
}

fn routine_boundary_comments(output: &CodegenOutput) -> BTreeMap<u16, Vec<String>> {
    let mut comments: BTreeMap<u16, Vec<String>> = BTreeMap::new();
    for routine in &output.map.routine_ranges {
        let entry = output
            .map
            .routine_addresses
            .iter()
            .find(|address| address.name.eq_ignore_ascii_case(&routine.name))
            .map(|address| address.address);
        comments
            .entry(routine.start)
            .or_default()
            .push(format_routine_start_comment(
                &routine.name,
                routine.start,
                routine.end,
                entry,
            ));
        comments
            .entry(routine.end)
            .or_default()
            .push(format!("; ===== END PROC {} =====", routine.name));
    }
    comments
}

fn format_routine_start_comment(name: &str, start: u16, end: u16, entry: Option<u16>) -> String {
    match entry {
        Some(entry) if entry != start => {
            format!("; ===== PROC {name} ${start:04X}..${end:04X} entry ${entry:04X} =====")
        }
        _ => format!("; ===== PROC {name} ${start:04X}..${end:04X} ====="),
    }
}

fn append_trailing_boundary_comments(
    output: &CodegenOutput,
    boundary_comments: &BTreeMap<u16, Vec<String>>,
    lines: &mut Vec<String>,
) {
    let end = output
        .origin
        .wrapping_add(u16::try_from(output.bytes.len()).unwrap_or(u16::MAX));
    if let Some(comments) = boundary_comments.get(&end) {
        push_assembly_comments(lines, comments);
    }
}

fn push_assembly_comments(lines: &mut Vec<String>, comments: &[String]) {
    lines.extend(
        comments
            .iter()
            .map(|comment| sanitize_assembly_comment(comment)),
    );
}

fn sanitize_assembly_comment(comment: &str) -> String {
    sanitize_comment_text(comment)
}

fn sanitize_comment_text(text: &str) -> String {
    let mut sanitized = String::new();
    for character in text.chars() {
        match character {
            ' '..='~' => sanitized.push(character),
            '\t' => sanitized.push_str("\\t"),
            '\r' => sanitized.push_str("\\r"),
            '\n' => sanitized.push_str("\\n"),
            character if character.is_ascii() => {
                sanitized.push_str(&format!("\\x{:02X}", character as u32));
            }
            character => sanitized.push_str(&format!("\\u{{{:X}}}", character as u32)),
        }
    }
    sanitized
}

fn format_source_range_kind(kind: CodegenSourceRangeKind) -> &'static str {
    match kind {
        CodegenSourceRangeKind::Routine => "routine",
        CodegenSourceRangeKind::Statement => "statement",
        CodegenSourceRangeKind::Expression => "expression",
        CodegenSourceRangeKind::Declaration => "declaration",
        CodegenSourceRangeKind::StorageInitializer => "storage",
        CodegenSourceRangeKind::MachineBlock => "machine",
    }
}
