use std::collections::{BTreeMap, BTreeSet};

use crate::codegen::{
    AddressingMode, CodegenOutput, CodegenRelocation, CodegenRelocationKind,
    CodegenSourceRangeKind, CodegenSymbolKind, CodegenSymbolScope, DisassembledInstruction,
    disassemble_with_origin_and_inline_jsr_data,
};
use crate::map_query::MapQuery;

pub(crate) fn format_listing_with_source(output: &CodegenOutput, source_text: &str) -> String {
    format_mads_listing(output, Some(source_text))
}

pub(crate) fn format_listing_with_boundaries(output: &CodegenOutput) -> String {
    format_mads_listing(output, None)
}

fn format_mads_listing(output: &CodegenOutput, source_text: Option<&str>) -> String {
    let boundary_comments = routine_boundary_comments(output);
    let instructions = disassemble_code_ranges(output);
    let items = listing_items(output, &instructions);
    let display_symbols = MadsDisplaySymbols::from_output(output, &instructions);
    let relocations = MadsRelocations::from_output(output);
    let routine_labels = routine_address_labels(output);
    let query = source_text.map(|source| MapQuery::with_source(&output.map, source));
    let mut last_source = None;
    let mut lines = vec![
        "; Generated by actionc. Re-originable MADS assembly listing.".to_string(),
        format!("; Runtime: {}", output.map.runtime),
        "; Change only ACTIONC_ORIGIN to move the generated main segment.".to_string(),
        "; Fixed numeric addresses and the RUNAD segment do not move.".to_string(),
        "; Address and byte comments describe the original actionc artifact.".to_string(),
        String::new(),
        format!("ACTIONC_ORIGIN = ${:04X}", output.origin),
        "        ORG ACTIONC_ORIGIN".to_string(),
        String::new(),
    ];
    for binding in &output.map.runtime_bindings {
        let target = binding
            .address
            .map(|address| format!("${address:04X}"))
            .unwrap_or_else(|| binding.implementation.clone());
        lines.push(sanitize_assembly_comment(&format!(
            "; Runtime binding: {} -> {} [{}] ({}){}",
            binding.helper,
            target,
            binding.origin,
            binding.reason,
            binding
                .suppressed_default
                .as_ref()
                .map(|default| format!("; suppresses {default}"))
                .unwrap_or_default()
        )));
    }
    if !output.map.runtime_bindings.is_empty() {
        lines.push(String::new());
    }
    display_symbols.push_equates(&mut lines);

    for item in items {
        match item {
            ListingItem::Instruction(instruction) => {
                if let Some(comments) = boundary_comments.get(&instruction.address) {
                    push_assembly_comments(&mut lines, comments);
                }
                display_symbols.push_definitions(instruction.address, &mut lines);
                if let Some(query) = &query {
                    push_source_comment(query, instruction.address, &mut last_source, &mut lines);
                }
                lines.push(format_instruction_listing(
                    &instruction,
                    output,
                    &display_symbols,
                    &relocations,
                    &routine_labels,
                ));
            }
            ListingItem::Data {
                address,
                bytes,
                name,
            } => {
                if let Some(comments) = boundary_comments.get(&address) {
                    push_assembly_comments(&mut lines, comments);
                }
                if let Some(query) = &query {
                    push_source_comment(query, address, &mut last_source, &mut lines);
                }
                if let Some(name) = name {
                    lines.push(sanitize_assembly_comment(&format!(
                        "; ===== DATA {name} ${address:04X} ====="
                    )));
                }
                push_data_listing(
                    output,
                    address,
                    &bytes,
                    &display_symbols,
                    &relocations,
                    &mut lines,
                );
            }
        }
    }

    if let Some(end) = output.origin.checked_add(output.bytes.len() as u16) {
        display_symbols.push_definitions(end, &mut lines);
    }
    append_trailing_boundary_comments(output, &boundary_comments, &mut lines);
    lines.push(String::new());
    lines.push("; Atari RUNAD segment.".to_string());
    lines.push("        ORG $02E2".to_string());
    let run_address = display_symbols
        .code_reference(output.run_address)
        .map(str::to_string)
        .unwrap_or_else(|| format!("${:04X}", output.run_address));
    lines.push(format!("        DTA A({run_address})"));
    lines.join("\n")
}

#[derive(Debug, Default)]
struct MadsDisplaySymbols {
    code_references: BTreeMap<u16, String>,
    global_storage_references: BTreeMap<u16, String>,
    routine_storage_references: BTreeMap<(String, u16), String>,
    storage_ranges: Vec<DisplayStorageRange>,
    synthetic_references: BTreeMap<u16, String>,
    routine_ranges: Vec<(u16, u16, String)>,
    definitions: BTreeMap<u16, Vec<String>>,
    equates: Vec<(String, u16)>,
    origin_equates: Vec<(String, u16)>,
    output_origin: u16,
    output_len: usize,
}

#[derive(Debug)]
struct DisplayStorageRange {
    start: u16,
    end: u16,
    routine: Option<String>,
    name: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum SyntheticTargetKind {
    Code,
    Data,
}

impl MadsDisplaySymbols {
    fn from_output(output: &CodegenOutput, instructions: &[DisassembledInstruction]) -> Self {
        let mut used_names = BTreeSet::new();
        let relocation_targets = output
            .relocations
            .iter()
            .filter_map(|relocation| output.origin.checked_add(relocation.target_offset))
            .collect::<BTreeSet<_>>();
        let mut symbols = Self {
            routine_ranges: output
                .map
                .routine_ranges
                .iter()
                .map(|range| (range.start, range.end, range.name.to_ascii_lowercase()))
                .collect(),
            output_origin: output.origin,
            output_len: output.bytes.len(),
            ..Self::default()
        };

        let mut routines = output.map.routine_addresses.iter().collect::<Vec<_>>();
        routines.sort_by(|left, right| {
            left.address
                .cmp(&right.address)
                .then_with(|| left.name.cmp(&right.name))
        });
        for routine in routines {
            if is_pseudo_routine_name(&routine.name) {
                continue;
            }
            let base = routine_symbol_base(&routine.name);
            let name = allocate_mads_symbol(&base, &mut used_names);
            symbols
                .code_references
                .entry(routine.address)
                .or_insert_with(|| name.clone());
            symbols.add_semantic_symbol(
                name,
                routine.address,
                relocation_targets.contains(&routine.address),
            );
        }

        let mut storage = output.map.storage_symbols.iter().collect::<Vec<_>>();
        storage.sort_by(|left, right| {
            left.address
                .cmp(&right.address)
                .then_with(|| storage_symbol_base(left).cmp(&storage_symbol_base(right)))
        });
        for symbol in storage {
            let base = storage_symbol_base(symbol);
            let name = allocate_mads_symbol(&base, &mut used_names);
            let routine = match &symbol.scope {
                CodegenSymbolScope::Global => None,
                CodegenSymbolScope::Routine(routine) => Some(routine.to_ascii_lowercase()),
            };
            match &symbol.scope {
                CodegenSymbolScope::Global => {
                    symbols
                        .global_storage_references
                        .entry(symbol.address)
                        .or_insert_with(|| name.clone());
                }
                CodegenSymbolScope::Routine(routine) => {
                    symbols
                        .routine_storage_references
                        .entry((routine.to_ascii_lowercase(), symbol.address))
                        .or_insert_with(|| name.clone());
                }
            }
            let end = symbol.address.saturating_add(symbol.size);
            let output_relative = relocation_targets
                .iter()
                .any(|target| *target >= symbol.address && *target < end);
            symbols.storage_ranges.push(DisplayStorageRange {
                start: symbol.address,
                end,
                routine,
                name: name.clone(),
            });
            symbols.add_semantic_symbol(name, symbol.address, output_relative);
        }

        let instruction_addresses = instructions
            .iter()
            .map(|instruction| instruction.address)
            .collect::<BTreeSet<_>>();
        let mut synthetic_targets = BTreeMap::new();
        for instruction in instructions {
            let Some(target) = instruction_target(instruction) else {
                continue;
            };
            if !instruction_addresses.contains(&target) {
                continue;
            }
            if symbols
                .internal_reference(target, instruction.address)
                .is_some()
            {
                continue;
            }
            synthetic_targets.insert(target, SyntheticTargetKind::Code);
        }
        for relocation in &output.relocations {
            let Some(base_target) = output.origin.checked_add(relocation.target_offset) else {
                continue;
            };
            if symbols
                .internal_reference(base_target, base_target)
                .is_some()
            {
                continue;
            }
            let target = if symbols.routine_name_at(base_target).is_some()
                && !instruction_addresses.contains(&base_target)
                && relocation.addend != 0
            {
                i32::from(base_target)
                    .checked_add(relocation.addend)
                    .and_then(|target| u16::try_from(target).ok())
                    .unwrap_or(base_target)
            } else {
                base_target
            };
            if symbols.internal_reference(target, target).is_some() {
                continue;
            }
            let kind = if symbols.routine_name_at(target).is_some() {
                SyntheticTargetKind::Code
            } else {
                SyntheticTargetKind::Data
            };
            synthetic_targets.entry(target).or_insert(kind);
        }

        let mut scope_ordinals = BTreeMap::<String, usize>::new();
        let mut data_ordinal = 0usize;
        for (target, kind) in synthetic_targets {
            let name = match kind {
                SyntheticTargetKind::Code => {
                    let scope = symbols
                        .routine_name_at(target)
                        .map(routine_symbol_component)
                        .unwrap_or_else(|| "program".to_string());
                    let ordinal = scope_ordinals.entry(scope.clone()).or_default();
                    *ordinal += 1;
                    allocate_mads_symbol(&format!("loc_{scope}_{ordinal}"), &mut used_names)
                }
                SyntheticTargetKind::Data => {
                    data_ordinal += 1;
                    allocate_mads_symbol(&format!("data_generated_{data_ordinal}"), &mut used_names)
                }
            };
            symbols.synthetic_references.insert(target, name.clone());
            if symbols.contains_output_boundary(target) {
                symbols.definitions.entry(target).or_default().push(name);
            } else if let Some(offset) = target.checked_sub(output.origin) {
                symbols.origin_equates.push((name, offset));
            }
        }

        for definitions in symbols.definitions.values_mut() {
            definitions.sort();
            definitions.dedup();
        }
        symbols
            .equates
            .sort_by(|left, right| left.1.cmp(&right.1).then_with(|| left.0.cmp(&right.0)));
        symbols
            .origin_equates
            .sort_by(|left, right| left.1.cmp(&right.1).then_with(|| left.0.cmp(&right.0)));
        symbols.storage_ranges.sort_by(|left, right| {
            left.start
                .cmp(&right.start)
                .then_with(|| left.end.cmp(&right.end))
                .then_with(|| left.name.cmp(&right.name))
        });
        symbols
    }

    fn add_semantic_symbol(&mut self, name: String, address: u16, output_relative: bool) {
        if self.contains_output_boundary(address) {
            self.definitions.entry(address).or_default().push(name);
        } else if output_relative && let Some(offset) = address.checked_sub(self.output_origin) {
            self.origin_equates.push((name, offset));
        } else {
            self.equates.push((name, address));
        }
    }

    fn push_equates(&self, lines: &mut Vec<String>) {
        if self.equates.is_empty() && self.origin_equates.is_empty() {
            return;
        }
        lines.push("; Semantic symbols outside the emitted main segment.".to_string());
        lines.extend(
            self.equates
                .iter()
                .map(|(name, address)| format!("{name} = ${address:04X}")),
        );
        lines.extend(self.origin_equates.iter().map(|(name, offset)| {
            if *offset == 0 {
                format!("{name} = ACTIONC_ORIGIN")
            } else {
                format!("{name} = ACTIONC_ORIGIN + ${offset:04X}")
            }
        }));
        lines.push(String::new());
    }

    fn push_definitions(&self, address: u16, lines: &mut Vec<String>) {
        if let Some(definitions) = self.definitions.get(&address) {
            lines.extend(definitions.iter().map(|name| format!("{name}:")));
        }
    }

    fn code_reference(&self, address: u16) -> Option<&str> {
        self.code_references
            .get(&address)
            .or_else(|| self.synthetic_references.get(&address))
            .map(String::as_str)
    }

    fn fixed_storage_reference(&self, address: u16, instruction_address: u16) -> Option<&str> {
        if self.contains_output_address(address) {
            return None;
        }
        self.routine_ranges
            .iter()
            .filter(|(start, end, _)| instruction_address >= *start && instruction_address < *end)
            .find_map(|(_, _, routine)| {
                self.routine_storage_references
                    .get(&(routine.clone(), address))
            })
            .or_else(|| self.global_storage_references.get(&address))
            .map(String::as_str)
    }

    fn internal_reference(&self, address: u16, source_address: u16) -> Option<(&str, u16)> {
        if let Some(name) = self.code_references.get(&address) {
            return Some((name, 0));
        }
        if let Some(reference) = self.storage_range_reference(address, source_address) {
            return Some(reference);
        }
        self.synthetic_references
            .get(&address)
            .map(|name| (name.as_str(), 0))
    }

    fn storage_range_reference(&self, address: u16, source_address: u16) -> Option<(&str, u16)> {
        let source_routine = self.routine_name_at(source_address);
        self.storage_ranges
            .iter()
            .filter(|range| address >= range.start && address < range.end)
            .min_by_key(|range| {
                let scope_rank = match (&range.routine, source_routine) {
                    (Some(owner), Some(source)) if owner.eq_ignore_ascii_case(source) => 0,
                    (None, _) => 1,
                    _ => 2,
                };
                (
                    scope_rank,
                    range.end.saturating_sub(range.start),
                    u16::MAX.saturating_sub(range.start),
                    range.name.as_str(),
                )
            })
            .map(|range| (range.name.as_str(), address.saturating_sub(range.start)))
    }

    fn routine_name_at(&self, address: u16) -> Option<&str> {
        self.routine_ranges
            .iter()
            .find(|(start, end, _)| address >= *start && address < *end)
            .map(|(_, _, routine)| routine.as_str())
    }

    fn contains_output_address(&self, address: u16) -> bool {
        address
            .checked_sub(self.output_origin)
            .is_some_and(|offset| usize::from(offset) < self.output_len)
    }

    fn contains_output_boundary(&self, address: u16) -> bool {
        address
            .checked_sub(self.output_origin)
            .is_some_and(|offset| usize::from(offset) <= self.output_len)
    }

    fn next_definition_after(&self, address: u16, end: u16) -> Option<u16> {
        self.definitions
            .range(address.saturating_add(1)..end)
            .next()
            .map(|(address, _)| *address)
    }
}

#[derive(Debug)]
struct MadsRelocations<'a> {
    by_address: BTreeMap<u16, &'a CodegenRelocation>,
}

impl<'a> MadsRelocations<'a> {
    fn from_output(output: &'a CodegenOutput) -> Self {
        let by_address = output
            .relocations
            .iter()
            .filter_map(|relocation| {
                output
                    .origin
                    .checked_add(relocation.value_offset)
                    .map(|address| (address, relocation))
            })
            .collect();
        Self { by_address }
    }

    fn at(&self, address: u16) -> Option<&'a CodegenRelocation> {
        self.by_address.get(&address).copied()
    }

    fn next_at_or_after(&self, address: u16, end: u16) -> Option<u16> {
        self.by_address
            .range(address..end)
            .next()
            .map(|(address, _)| *address)
    }
}

fn relocation_expression(
    output: &CodegenOutput,
    symbols: &MadsDisplaySymbols,
    relocation: &CodegenRelocation,
    source_address: u16,
) -> Option<String> {
    let target = output.origin.checked_add(relocation.target_offset)?;
    if let Some((name, interior_offset)) = symbols.internal_reference(target, source_address) {
        return Some(format_symbol_addend(
            name,
            i32::from(interior_offset).checked_add(relocation.addend)?,
        ));
    }
    let final_target = i32::from(target)
        .checked_add(relocation.addend)
        .and_then(|target| u16::try_from(target).ok())?;
    let (name, interior_offset) = symbols.internal_reference(final_target, source_address)?;
    Some(format_symbol_addend(name, i32::from(interior_offset)))
}

fn format_symbol_addend(name: &str, addend: i32) -> String {
    match addend.cmp(&0) {
        std::cmp::Ordering::Less => format!("{name}-{}", addend.unsigned_abs()),
        std::cmp::Ordering::Equal => name.to_string(),
        std::cmp::Ordering::Greater => format!("{name}+{addend}"),
    }
}

fn is_pseudo_routine_name(name: &str) -> bool {
    name.starts_with('<') && name.ends_with('>')
}

fn routine_symbol_base(name: &str) -> String {
    format!("proc_{}", routine_symbol_component(name))
}

fn routine_symbol_component(name: &str) -> String {
    runtime_symbol_component(name).unwrap_or_else(|| sanitize_mads_component(name))
}

fn runtime_symbol_component(name: &str) -> Option<String> {
    let name = sanitize_mads_component(name);
    for (prefix, short_prefix, has_semantic_hash) in [
        ("m_action_runtime_syslib_", "syslib_", true),
        ("m_action_runtime_resident_", "resident_", true),
        ("action_runtime_syslib_", "syslib_", false),
        ("action_runtime_resident_", "resident_", false),
    ] {
        let Some(routine) = name.strip_prefix(prefix) else {
            continue;
        };
        let routine = if has_semantic_hash {
            strip_semantic_hash(routine)
        } else {
            routine
        };
        return Some(format!("{short_prefix}{routine}"));
    }
    None
}

fn strip_semantic_hash(name: &str) -> &str {
    let Some((stem, suffix)) = name.rsplit_once('_') else {
        return name;
    };
    if suffix.len() == 8 && suffix.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        stem
    } else {
        name
    }
}

fn storage_symbol_base(symbol: &crate::codegen::CodegenStorageSymbol) -> String {
    match &symbol.scope {
        CodegenSymbolScope::Global => {
            if let Some(static_name) = symbol.name.strip_prefix("__nir_str_") {
                format!("static_string_{}", sanitize_mads_component(static_name))
            } else {
                let name = runtime_symbol_component(&symbol.name)
                    .unwrap_or_else(|| sanitize_mads_component(&symbol.name));
                format!("global_{name}")
            }
        }
        CodegenSymbolScope::Routine(routine) => {
            let routine = routine_symbol_component(routine);
            let display_name = strip_routine_lexical_prefix(&symbol.name, &routine);
            let name = runtime_symbol_component(display_name)
                .and_then(|name| {
                    name.strip_prefix(&routine)
                        .and_then(|name| name.strip_prefix('_'))
                        .map(str::to_string)
                })
                .unwrap_or_else(|| sanitize_mads_component(display_name));
            match symbol.kind {
                CodegenSymbolKind::Parameter => format!("param_{routine}_{name}"),
                CodegenSymbolKind::Local if name.starts_with("spill") => {
                    format!("spill_{routine}_{}", name.trim_start_matches("spill"))
                }
                CodegenSymbolKind::Local => format!("local_{routine}_{name}"),
                CodegenSymbolKind::Storage => format!("storage_{routine}_{name}"),
            }
        }
    }
}

fn strip_routine_lexical_prefix<'a>(name: &'a str, routine: &str) -> &'a str {
    let Some((prefix, rest)) = name.split_once("::") else {
        return name;
    };
    if prefix.eq_ignore_ascii_case(routine) {
        rest
    } else {
        name
    }
}

fn sanitize_mads_component(value: &str) -> String {
    let mut sanitized = String::new();
    let mut previous_was_separator = false;
    for character in value.chars() {
        if character.is_ascii_alphanumeric() || character == '_' {
            sanitized.push(character.to_ascii_lowercase());
            previous_was_separator = false;
        } else if !previous_was_separator {
            sanitized.push('_');
            previous_was_separator = true;
        }
    }
    let sanitized = sanitized.trim_matches('_');
    if sanitized.is_empty() {
        "unnamed".to_string()
    } else {
        sanitized.to_string()
    }
}

fn allocate_mads_symbol(base: &str, used_names: &mut BTreeSet<String>) -> String {
    let normalized = base.to_ascii_lowercase();
    if used_names.insert(normalized) {
        return base.to_string();
    }
    for suffix in 2usize.. {
        let candidate = format!("{base}__{suffix}");
        if used_names.insert(candidate.to_ascii_lowercase()) {
            return candidate;
        }
    }
    unreachable!("MADS display-symbol suffix space is unbounded")
}

#[derive(Debug, Clone)]
enum ListingItem {
    Instruction(DisassembledInstruction),
    Data {
        address: u16,
        bytes: Vec<u8>,
        name: Option<String>,
    },
}

fn listing_items(
    output: &CodegenOutput,
    instructions: &[DisassembledInstruction],
) -> Vec<ListingItem> {
    let mut items = Vec::new();
    let mut instruction_index = 0;
    let mut cursor = output.origin;
    let end = output
        .origin
        .wrapping_add(u16::try_from(output.bytes.len()).unwrap_or(u16::MAX));
    let storage = storage_listing_ranges(output);
    let mut storage_index = 0;

    while cursor < end {
        if let Some(symbol) = storage.get(storage_index)
            && symbol.address == cursor
        {
            items.push(ListingItem::Data {
                address: symbol.address,
                bytes: symbol.bytes.clone(),
                name: Some(symbol.name.clone()),
            });
            cursor = symbol.address.saturating_add(symbol.bytes.len() as u16);
            storage_index += 1;
            continue;
        }

        while let Some(instruction) = instructions.get(instruction_index)
            && instruction.address < cursor
        {
            instruction_index += 1;
        }

        if let Some(instruction) = instructions.get(instruction_index)
            && instruction.address == cursor
        {
            items.push(ListingItem::Instruction(instruction.clone()));
            cursor = cursor.saturating_add(instruction.bytes.len() as u16);
            instruction_index += 1;
            continue;
        }

        let Some(offset) = output_offset(output, cursor) else {
            break;
        };
        let len = output
            .relocations
            .iter()
            .find(|relocation| usize::from(relocation.value_offset) == offset)
            .map(|relocation| usize::from(relocation.kind.width()))
            .unwrap_or(1)
            .min(output.bytes.len().saturating_sub(offset));
        items.push(ListingItem::Data {
            address: cursor,
            bytes: output.bytes[offset..offset + len].to_vec(),
            name: None,
        });
        cursor = cursor.saturating_add(len as u16);
    }

    items
}

#[derive(Debug, Clone)]
struct StorageListingRange {
    address: u16,
    bytes: Vec<u8>,
    name: String,
}

fn storage_listing_ranges(output: &CodegenOutput) -> Vec<StorageListingRange> {
    let mut ranges = output
        .map
        .storage_symbols
        .iter()
        .filter(|symbol| !address_in_routine(output, symbol.address))
        .filter_map(|symbol| {
            let start = output_offset(output, symbol.address)?;
            let end = start.saturating_add(symbol.size as usize);
            let bytes = output.bytes.get(start..end)?.to_vec();
            Some(StorageListingRange {
                address: symbol.address,
                bytes,
                name: symbol.name.clone(),
            })
        })
        .collect::<Vec<_>>();
    ranges.extend(storage_source_listing_ranges(output));
    ranges.sort_by_key(|range| range.address);
    ranges.dedup_by_key(|range| range.address);
    ranges
}

fn storage_source_listing_ranges(output: &CodegenOutput) -> Vec<StorageListingRange> {
    output
        .map
        .source_ranges
        .iter()
        .filter(|range| range.kind == CodegenSourceRangeKind::StorageInitializer)
        .filter_map(|range| {
            let start = output_offset(output, range.start)?;
            let end = output_end_offset(output, range.end)?;
            let bytes = output.bytes.get(start..end)?.to_vec();
            (!bytes.is_empty()).then(|| StorageListingRange {
                address: range.start,
                bytes,
                name: range.name.clone().unwrap_or_else(|| "storage".to_string()),
            })
        })
        .collect()
}

fn disassemble_code_ranges(output: &CodegenOutput) -> Vec<DisassembledInstruction> {
    let mut ranges = output.map.routine_ranges.clone();
    ranges.sort_by_key(|range| range.start);
    let mut storage = storage_source_listing_ranges(output);
    storage.sort_by_key(|range| range.address);
    let inline_jsr_data_lengths = inline_jsr_data_lengths(output);
    let mut instructions = Vec::new();
    for range in ranges {
        let mut cursor = range.start;
        for data in storage.iter().filter(|data| {
            let data_end = data.address.saturating_add(data.bytes.len() as u16);
            data.address < range.end && data_end > range.start
        }) {
            if data.address > cursor {
                push_disassembled_range(
                    output,
                    cursor,
                    data.address,
                    &inline_jsr_data_lengths,
                    &mut instructions,
                );
            }
            cursor = cursor.max(data.address.saturating_add(data.bytes.len() as u16));
        }
        if cursor < range.end {
            push_disassembled_range(
                output,
                cursor,
                range.end,
                &inline_jsr_data_lengths,
                &mut instructions,
            );
        }
    }
    instructions
}

fn push_disassembled_range(
    output: &CodegenOutput,
    start_address: u16,
    end_address: u16,
    inline_jsr_data_lengths: &BTreeMap<u16, usize>,
    instructions: &mut Vec<DisassembledInstruction>,
) {
    if end_address <= start_address {
        return;
    }
    let Some(start) = output_offset(output, start_address) else {
        return;
    };
    let Some(end) = output_end_offset(output, end_address) else {
        return;
    };
    instructions.extend(disassemble_with_origin_and_inline_jsr_data(
        output.bytes.get(start..end).unwrap_or_default(),
        start_address,
        |target| inline_jsr_data_lengths.get(&target).copied(),
    ));
}

fn inline_jsr_data_lengths(output: &CodegenOutput) -> BTreeMap<u16, usize> {
    output
        .map
        .routine_addresses
        .iter()
        // Action! r_Par consumes three inline parameter bytes after the JSR.
        .filter(|routine| routine.name.eq_ignore_ascii_case("r_Par"))
        .map(|routine| (routine.address, 3))
        .collect()
}

fn address_in_routine(output: &CodegenOutput, address: u16) -> bool {
    output
        .map
        .routine_ranges
        .iter()
        .any(|range| address >= range.start && address < range.end)
}

fn output_offset(output: &CodegenOutput, address: u16) -> Option<usize> {
    if address < output.origin {
        return None;
    }
    let offset = address.wrapping_sub(output.origin) as usize;
    (offset < output.bytes.len()).then_some(offset)
}

fn output_end_offset(output: &CodegenOutput, address: u16) -> Option<usize> {
    if address < output.origin {
        return None;
    }
    let offset = address.wrapping_sub(output.origin) as usize;
    (offset <= output.bytes.len()).then_some(offset)
}

fn push_source_comment(
    query: &MapQuery<'_>,
    address: u16,
    last_source: &mut Option<(usize, usize, u16, u16)>,
    lines: &mut Vec<String>,
) {
    let Some(source) = query.source_at(address) else {
        return;
    };
    let range = source.range;
    let key = (
        range.source_span.start,
        range.source_span.end,
        range.start,
        range.end,
    );
    if *last_source == Some(key) {
        return;
    }
    *last_source = Some(key);
    if let Some(location) = source.location {
        lines.push(sanitize_assembly_comment(&format!(
            "; {}:{} {}{} | {}",
            location.line,
            location.column,
            format_source_range_kind(range.kind),
            range
                .name
                .as_ref()
                .map(|name| format!(" {name}"))
                .unwrap_or_default(),
            location.excerpt
        )));
    }
}

fn format_instruction_listing(
    instruction: &DisassembledInstruction,
    output: &CodegenOutput,
    display_symbols: &MadsDisplaySymbols,
    relocations: &MadsRelocations<'_>,
    routine_labels: &BTreeMap<u16, String>,
) -> String {
    let assembly = format_mads_instruction(instruction, output, display_symbols, relocations);
    let annotation = if instruction.mnemonic == "JSR"
        && let Some(target) = le_u16_from_slice(&instruction.operands)
        && let Some(label) = routine_labels.get(&target)
    {
        Some(label.as_str())
    } else {
        None
    };
    format_assembly_line(
        &assembly,
        instruction.address,
        &instruction.bytes,
        annotation,
    )
}

fn push_data_listing(
    output: &CodegenOutput,
    address: u16,
    bytes: &[u8],
    display_symbols: &MadsDisplaySymbols,
    relocations: &MadsRelocations<'_>,
    lines: &mut Vec<String>,
) {
    let Some(end) = address.checked_add(bytes.len() as u16) else {
        lines.push(format_assembly_line(
            &format_byte_directive(bytes),
            address,
            bytes,
            None,
        ));
        return;
    };
    let mut cursor = address;
    while cursor < end {
        display_symbols.push_definitions(cursor, lines);
        let offset = usize::from(cursor - address);
        if let Some(relocation) = relocations.at(cursor)
            && let Some(expression) =
                relocation_expression(output, display_symbols, relocation, cursor)
        {
            let width = usize::from(relocation.kind.width());
            if offset + width <= bytes.len() {
                let directive = match relocation.kind {
                    CodegenRelocationKind::Word16 => format!("DTA A({expression})"),
                    CodegenRelocationKind::Address8 => format!("DTA B({expression})"),
                    CodegenRelocationKind::Low8 => format!("DTA L({expression})"),
                    CodegenRelocationKind::High8 => format!("DTA H({expression})"),
                    CodegenRelocationKind::Relative8 => {
                        format!("DTA B({expression}-(*+1))")
                    }
                };
                lines.push(format_assembly_line(
                    &directive,
                    cursor,
                    &bytes[offset..offset + width],
                    None,
                ));
                cursor = cursor.saturating_add(width as u16);
                continue;
            }
        }

        let literal_end = cursor
            .saturating_add(8)
            .min(end)
            .min(
                relocations
                    .next_at_or_after(cursor.saturating_add(1), end)
                    .unwrap_or(end),
            )
            .min(
                display_symbols
                    .next_definition_after(cursor, end)
                    .unwrap_or(end),
            );
        let literal_end = literal_end.max(cursor.saturating_add(1));
        let literal_offset_end = usize::from(literal_end - address);
        lines.push(format_assembly_line(
            &format_byte_directive(&bytes[offset..literal_offset_end]),
            cursor,
            &bytes[offset..literal_offset_end],
            None,
        ));
        cursor = literal_end;
    }
}

fn format_mads_instruction(
    instruction: &DisassembledInstruction,
    output: &CodegenOutput,
    display_symbols: &MadsDisplaySymbols,
    relocations: &MadsRelocations<'_>,
) -> String {
    let Some(mode) = instruction.mode else {
        return format_byte_directive(&instruction.bytes);
    };
    let mnemonic = instruction.mnemonic;
    let byte = || {
        *instruction
            .operands
            .first()
            .expect("decoded byte operand must be present")
    };
    let word =
        || le_u16_from_slice(&instruction.operands).expect("decoded word operand must be present");
    let relocation = instruction
        .address
        .checked_add(1)
        .and_then(|address| relocations.at(address));
    let relocated = relocation.and_then(|relocation| {
        relocation_expression(output, display_symbols, relocation, instruction.address)
            .map(|expression| (relocation.kind, expression))
    });

    match mode {
        AddressingMode::Implied | AddressingMode::Accumulator => mnemonic.to_string(),
        AddressingMode::Immediate => match relocated {
            Some((CodegenRelocationKind::Address8, expression)) => {
                format!("{mnemonic} #{expression}")
            }
            Some((CodegenRelocationKind::Low8, expression)) => {
                format!("{mnemonic} #<({expression})")
            }
            Some((CodegenRelocationKind::High8, expression)) => {
                format!("{mnemonic} #>({expression})")
            }
            _ => format!("{mnemonic} #${:02X}", byte()),
        },
        AddressingMode::ZeroPage => format!(
            "{mnemonic}.Z {}",
            byte_address_operand(
                display_symbols,
                relocated,
                u16::from(byte()),
                instruction.address,
            )
        ),
        AddressingMode::ZeroPageX => format!(
            "{mnemonic}.Z {},X",
            byte_address_operand(
                display_symbols,
                relocated,
                u16::from(byte()),
                instruction.address,
            )
        ),
        AddressingMode::ZeroPageY => format!(
            "{mnemonic}.Z {},Y",
            byte_address_operand(
                display_symbols,
                relocated,
                u16::from(byte()),
                instruction.address,
            )
        ),
        AddressingMode::Absolute => {
            let target = word();
            let operand = word_address_operand(
                display_symbols,
                relocated,
                target,
                instruction.address,
                matches!(mnemonic, "JMP" | "JSR"),
            );
            format!("{mnemonic}.A {operand}")
        }
        AddressingMode::AbsoluteX => format!(
            "{mnemonic}.A {},X",
            word_address_operand(
                display_symbols,
                relocated,
                word(),
                instruction.address,
                false,
            )
        ),
        AddressingMode::AbsoluteY => format!(
            "{mnemonic}.A {},Y",
            word_address_operand(
                display_symbols,
                relocated,
                word(),
                instruction.address,
                false,
            )
        ),
        AddressingMode::Indirect => format!(
            "{mnemonic} ({})",
            word_address_operand(
                display_symbols,
                relocated,
                word(),
                instruction.address,
                false,
            )
        ),
        AddressingMode::IndexedIndirectX => format!(
            "{mnemonic} ({},X)",
            byte_address_operand(
                display_symbols,
                relocated,
                u16::from(byte()),
                instruction.address,
            )
        ),
        AddressingMode::IndirectIndexedY => format!(
            "{mnemonic} ({}),Y",
            byte_address_operand(
                display_symbols,
                relocated,
                u16::from(byte()),
                instruction.address,
            )
        ),
        AddressingMode::Relative => {
            let target = instruction
                .address
                .wrapping_add(2)
                .wrapping_add_signed(i16::from(byte() as i8));
            let operand = match relocated {
                Some((CodegenRelocationKind::Relative8, expression)) => expression,
                _ => display_symbols
                    .code_reference(target)
                    .map(str::to_string)
                    .unwrap_or_else(|| format!("${target:04X}")),
            };
            format!("{mnemonic} {operand}")
        }
    }
}

fn byte_address_operand(
    symbols: &MadsDisplaySymbols,
    relocated: Option<(CodegenRelocationKind, String)>,
    address: u16,
    instruction_address: u16,
) -> String {
    match relocated {
        Some((CodegenRelocationKind::Address8, expression)) => expression,
        Some((CodegenRelocationKind::Low8, expression)) => format!("<({expression})"),
        Some((CodegenRelocationKind::High8, expression)) => format!(">({expression})"),
        _ => symbols
            .fixed_storage_reference(address, instruction_address)
            .map(str::to_string)
            .unwrap_or_else(|| format!("${address:02X}")),
    }
}

fn word_address_operand(
    symbols: &MadsDisplaySymbols,
    relocated: Option<(CodegenRelocationKind, String)>,
    address: u16,
    instruction_address: u16,
    code: bool,
) -> String {
    if let Some((CodegenRelocationKind::Word16, expression)) = relocated {
        return expression;
    }
    if code && !symbols.contains_output_address(address) {
        return symbols
            .code_reference(address)
            .map(str::to_string)
            .unwrap_or_else(|| format!("${address:04X}"));
    }
    symbols
        .fixed_storage_reference(address, instruction_address)
        .map(str::to_string)
        .unwrap_or_else(|| format!("${address:04X}"))
}

fn format_byte_directive(bytes: &[u8]) -> String {
    let values = bytes
        .iter()
        .map(|byte| format!("${byte:02X}"))
        .collect::<Vec<_>>()
        .join(",");
    format!(".BYTE {values}")
}

fn format_assembly_line(
    assembly: &str,
    address: u16,
    bytes: &[u8],
    annotation: Option<&str>,
) -> String {
    let raw = bytes
        .iter()
        .map(|byte| format!("{byte:02X}"))
        .collect::<Vec<_>>()
        .join(" ");
    let annotation = annotation
        .map(sanitize_comment_text)
        .map(|text| format!(" ; {text}"))
        .unwrap_or_default();
    format!("        {assembly:<36} ; ${address:04X}: {raw}{annotation}")
}

fn routine_address_labels(output: &CodegenOutput) -> BTreeMap<u16, String> {
    output
        .map
        .routine_addresses
        .iter()
        .map(|routine| (routine.address, routine.name.clone()))
        .collect()
}

fn instruction_target(item: &DisassembledInstruction) -> Option<u16> {
    match item.mode? {
        AddressingMode::Relative => {
            let offset = *item.operands.first()? as i8;
            Some(
                item.address
                    .wrapping_add(2)
                    .wrapping_add_signed(i16::from(offset)),
            )
        }
        AddressingMode::Absolute | AddressingMode::AbsoluteX => {
            if matches!(item.mnemonic, "JMP" | "JSR") {
                le_u16_from_slice(&item.operands)
            } else {
                None
            }
        }
        _ => None,
    }
}

fn le_u16_from_slice(bytes: &[u8]) -> Option<u16> {
    Some(u16::from(*bytes.first()?) | (u16::from(*bytes.get(1)?) << 8))
}

fn routine_boundary_comments(output: &CodegenOutput) -> BTreeMap<u16, Vec<String>> {
    let mut comments: BTreeMap<u16, Vec<String>> = BTreeMap::new();
    for routine in &output.map.routine_ranges {
        let entry = output
            .map
            .routine_addresses
            .iter()
            .find(|address| address.name.eq_ignore_ascii_case(&routine.name))
            .map(|address| address.address);
        comments
            .entry(routine.start)
            .or_default()
            .push(format_routine_start_comment(
                &routine.name,
                routine.start,
                routine.end,
                entry,
            ));
        comments
            .entry(routine.end)
            .or_default()
            .push(format!("; ===== END PROC {} =====", routine.name));
    }
    comments
}

fn format_routine_start_comment(name: &str, start: u16, end: u16, entry: Option<u16>) -> String {
    match entry {
        Some(entry) if entry != start => {
            format!("; ===== PROC {name} ${start:04X}..${end:04X} entry ${entry:04X} =====")
        }
        _ => format!("; ===== PROC {name} ${start:04X}..${end:04X} ====="),
    }
}

fn append_trailing_boundary_comments(
    output: &CodegenOutput,
    boundary_comments: &BTreeMap<u16, Vec<String>>,
    lines: &mut Vec<String>,
) {
    let end = output
        .origin
        .wrapping_add(u16::try_from(output.bytes.len()).unwrap_or(u16::MAX));
    if let Some(comments) = boundary_comments.get(&end) {
        push_assembly_comments(lines, comments);
    }
}

fn push_assembly_comments(lines: &mut Vec<String>, comments: &[String]) {
    lines.extend(
        comments
            .iter()
            .map(|comment| sanitize_assembly_comment(comment)),
    );
}

fn sanitize_assembly_comment(comment: &str) -> String {
    sanitize_comment_text(comment)
}

fn sanitize_comment_text(text: &str) -> String {
    let mut sanitized = String::new();
    for character in text.chars() {
        match character {
            ' '..='~' => sanitized.push(character),
            '\t' => sanitized.push_str("\\t"),
            '\r' => sanitized.push_str("\\r"),
            '\n' => sanitized.push_str("\\n"),
            character if character.is_ascii() => {
                sanitized.push_str(&format!("\\x{:02X}", character as u32));
            }
            character => sanitized.push_str(&format!("\\u{{{:X}}}", character as u32)),
        }
    }
    sanitized
}

fn format_source_range_kind(kind: CodegenSourceRangeKind) -> &'static str {
    match kind {
        CodegenSourceRangeKind::Routine => "routine",
        CodegenSourceRangeKind::Statement => "statement",
        CodegenSourceRangeKind::Expression => "expression",
        CodegenSourceRangeKind::Declaration => "declaration",
        CodegenSourceRangeKind::StorageInitializer => "storage",
        CodegenSourceRangeKind::MachineBlock => "machine",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shortens_runtime_routine_and_storage_components() {
        assert_eq!(
            routine_symbol_component("M_ACTION_RUNTIME_SYSLIB_REMI_7A64A35C"),
            "syslib_remi"
        );
        assert_eq!(
            routine_symbol_component("ACTION.RUNTIME.RESIDENT::PrintC"),
            "resident_printc"
        );
        assert_eq!(
            runtime_symbol_component("M_ACTION_RUNTIME_RESIDENT_PRINTC_N_27014C22"),
            Some("resident_printc_n".to_string())
        );
        assert_eq!(
            runtime_symbol_component("M_ACTION_RUNTIME_RESIDENT_BUFFER_DEADBEEF"),
            Some("resident_buffer".to_string())
        );
    }
}
