#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: surveys/action-runtime/survey.sh [--output <report.md>] [--runtime-dir <dir>] [--modern-dir <dir>]

Survey the extracted official ACTION! RunTime Disk sources with the current
actionc. The report checks each selected .ACT file across the supported profile
and backend combinations:

  legacy + classic
  modern + classic
  modern + mir6502

SYSALL.ACT is the only SYS*.ACT source checked directly because it includes the
other SYS*.ACT runtime files.

Modernized source overlays are read from samples/action-runtime/modern by
default. When an overlay file exists, the survey compiles through a temporary
runtime directory containing the original runtime disk files plus that overlay,
so local INCLUDE directives still resolve against the runtime disk.

USAGE
}

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/../.." && pwd)"
runtime_dir="$repo_root/corpora/action-runtime/extracted"
modern_dir="$repo_root/samples/action-runtime/modern"
report="$script_dir/RUNTIME_DISK_SURVEY.md"

first_error() {
  local file="$1"
  local line
  line="$(sed -n '/[^[:space:]]/ { s/[[:space:]]\+/ /g; p; q; }' "$file")"
  if [ -z "$line" ]; then
    line="command failed without diagnostics"
  fi
  printf '%s' "$line"
}

escape_md() {
  local text="$1"
  text="${text//\\/\\\\}"
  text="${text//|/\\|}"
  printf '%s' "$text"
}

display_path() {
  local path="$1"
  case "$path" in
    "$repo_root"/*) printf '%s' "${path#"$repo_root"/}" ;;
    *) printf '%s' "$path" ;;
  esac
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --output)
      shift
      if [ "$#" -eq 0 ]; then
        echo "--output requires a path" >&2
        exit 2
      fi
      report="$1"
      ;;
    --runtime-dir)
      shift
      if [ "$#" -eq 0 ]; then
        echo "--runtime-dir requires a path" >&2
        exit 2
      fi
      runtime_dir="$1"
      ;;
    --modern-dir)
      shift
      if [ "$#" -eq 0 ]; then
        echo "--modern-dir requires a path" >&2
        exit 2
      fi
      modern_dir="$1"
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

if [ ! -d "$runtime_dir" ]; then
  echo "missing runtime disk directory: $runtime_dir" >&2
  exit 1
fi

cd "$repo_root"
cargo build --quiet
actionc="$repo_root/target/debug/actionc-emit"

tmp_dir="$(mktemp -d "${TMPDIR:-/tmp}/actionc-runtime-survey.XXXXXX")"
trap 'rm -rf "$tmp_dir"' EXIT

overlaid_runtime_dir="$tmp_dir/runtime"
mkdir -p "$overlaid_runtime_dir"
while IFS= read -r runtime_file; do
  ln -s "$runtime_file" "$overlaid_runtime_dir/$(basename "$runtime_file")"
done < <(find "$runtime_dir" -maxdepth 1 -type f | sort)

if [ -d "$modern_dir" ]; then
  while IFS= read -r overlay_file; do
    rm -f "$overlaid_runtime_dir/$(basename "$overlay_file")"
    ln -s "$overlay_file" "$overlaid_runtime_dir/$(basename "$overlay_file")"
  done < <(find "$modern_dir" -maxdepth 1 -type f | sort)
fi

sources=()
while IFS= read -r source_name; do
  case "$source_name" in
    SYS*.ACT)
      if [ "$source_name" != "SYSALL.ACT" ]; then
        continue
      fi
      ;;
  esac
  sources+=("$source_name")
done < <(
  {
    find "$runtime_dir" -maxdepth 1 -type f -name '*.ACT' -exec basename {} \;
    if [ -d "$modern_dir" ]; then
      find "$modern_dir" -maxdepth 1 -type f -name '*.ACT' -exec basename {} \;
    fi
  } | sort -u
)

config_profiles=(legacy modern modern)
config_backends=(classic classic mir6502)

{
  echo "# ACTION! RunTime Disk Survey"
  echo
  echo "Generated by \`surveys/action-runtime/survey.sh\`."
  echo
  echo "Runtime disk directory: \`$(display_path "$runtime_dir")\`"
  echo "Modern overlay directory: \`$(display_path "$modern_dir")\`"
  echo
  echo "Sweep policy:"
  echo
  echo "- \`SYSALL.ACT\` represents the SYS runtime family; individual \`SYS*.ACT\` files are not checked separately."
  echo "- Modernized files under \`$(display_path "$modern_dir")\` overlay the extracted runtime disk without modifying \`$(display_path "$runtime_dir")\`."
  echo "- Every checked source is compiled with the supported profile/backend combinations using \`--emit-source-listing\`."
  echo "- \`legacy\` + \`mir6502\` is skipped because the MIR6502 backend only supports the modern profile."
  echo
  echo "| Source | Actual Source | Profile | Backend | Status | Detail |"
  echo "| --- | --- | --- | --- | --- | --- |"
} > "$report"

configs=0
ok=0
failures=0

for name in "${sources[@]}"; do
  src="$runtime_dir/$name"
  actual_source="$src"
  compile_source="$src"
  if [ -f "$modern_dir/$name" ]; then
    actual_source="$modern_dir/$name"
    compile_source="$overlaid_runtime_dir/$name"
  fi

  for config_index in "${!config_profiles[@]}"; do
    profile="${config_profiles[$config_index]}"
    backend="${config_backends[$config_index]}"
    configs=$((configs + 1))
    err="$tmp_dir/$name.$profile.$backend.err"
    status="ok"
    detail="emits source listing"

    if ! "$actionc" --profile "$profile" --backend "$backend" --emit-source-listing "$compile_source" >/dev/null 2>"$err"; then
      status="blocked"
      detail="$(first_error "$err")"
      failures=$((failures + 1))
    else
      ok=$((ok + 1))
    fi

    printf '| `%s` | `%s` | `%s` | `%s` | %s | %s |\n' \
      "$name" "$(escape_md "$(display_path "$actual_source")")" "$profile" "$backend" "$status" "$(escape_md "$detail")" >> "$report"
  done
done

{
  echo
  echo "Summary:"
  echo
  echo "- Sources tracked: ${#sources[@]}"
  echo "- Profile/backend configurations: $configs"
  echo "- Source listings emitted: $ok"
  echo "- Blocked: $failures"
} >> "$report"

cat "$report"
