#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: surveys/toolkit/capture-original-demos.sh [name ...]

Compile Toolkit demo/program sources with the original Action! compiler VM.
Raw *.atascii sidecars are used for compiler input so inverse and control
characters match the original ATR contents. Each temporary source is prefixed
with:

  SET $491=$3000
  SET $E=$3000

so the original compiler writes a load segment anchored at $3000.

Artifacts are written to surveys/toolkit/outputs/vm:

  <stem>.COM
  <stem>.symbols.json
  <stem>.symbol-snapshots.json
  <stem>.capture.log
  <stem>.load-info.txt
  <stem>.compare.txt
  <stem>.source.atascii

Environment:
  ACTION_COMPILER_VM_DIR      default: ../action-compiler-vm
  ACTION_VM_CART              default: roms/action.rom
  ACTION_VM_OS                default: roms/rev02.rom
  ACTION_TOOLKIT_VM_MAX_STEPS default: 20000000
USAGE
}

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/../.." && pwd)"
toolkit_dir="$repo_root/corpora/toolkit/original/extracted"
out_dir="$script_dir/outputs/vm"
vm_root="${ACTION_COMPILER_VM_DIR:-$repo_root/../action-compiler-vm}"
cart_rom="${ACTION_VM_CART:-$repo_root/roms/action.rom}"
os_rom="${ACTION_VM_OS:-$repo_root/roms/rev02.rom}"
max_steps="${ACTION_TOOLKIT_VM_MAX_STEPS:-20000000}"

entries=(
  "CIRCLE1:CIRCLE.DM1:CIRCLE1.ACT:CIRCLE1.COM"
  "CIRCLE2:CIRCLE.DM2:CIRCLE2.ACT:CIRCLE2.COM"
  "GEMDEM:GEM.DEM:GEMDEM.ACT:GEMDEM.COM"
  "KALSCOPE:KALSCOPE.DEM:KALSCOPE.ACT:KALSCOPE.COM"
  "MUSICDEM:MUSIC.DEM:MUSICDEM.ACT:MUSICDEM.COM"
  "PMGDM1:PMG.DM1:PMGDM1.ACT:PMGDM1.COM"
  "PMGDM2:PMG.DM2:PMGDM2.ACT:PMGDM2.COM"
  "PRINTF1:PRINTF.DM1:PRINTF1.ACT:PRINTF1.COM"
  "REALDM1:REAL.DM1:REALDM1.ACT:REALDM1.COM"
  "SNAILS:SNAILS.DEM:SNAILS.ACT:SNAILS.COM"
  "SORTDM1:SORT.DM1:SORTDM1.ACT:SORTDM1.COM"
  "SORTDM2:SORT.DM2:SORTDM2.ACT:SORTDM2.COM"
  "TURTLE1:TURTLE.DM1:TURTLE1.ACT:TURTLE1.COM"
  "WARPDEM:WARP.DEM:WARPDEM.ACT:WARPDEM.COM"
)

require_file() {
  local path="$1"
  local label="$2"
  if [[ ! -f "$path" ]]; then
    echo "missing $label: $path" >&2
    exit 1
  fi
}

sanitize_capture_log() {
  local file="$1"
  local sanitized="$tmp_root/sanitized.$(basename "$file")"
  local line
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line//"$repo_root"\//}"
    line="${line//"$vm_root"/[action-compiler-vm]}"
    line="${line//"$tmp_root"/[tmp]}"
    printf '%s\n' "$line"
  done < "$file" > "$sanitized"
  mv "$sanitized" "$file"
}

entry_by_name() {
  local wanted="$1"
  local entry stem source host output
  for entry in "${entries[@]}"; do
    IFS=: read -r stem source host output <<<"$entry"
    if [[ "$wanted" == "$stem" || "$wanted" == "$source" || "$wanted" == "$output" ]]; then
      printf '%s\n' "$entry"
      return 0
    fi
  done
  return 1
}

selected=()
if [[ $# -eq 0 ]]; then
  selected=("${entries[@]}")
else
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h|--help)
        usage
        exit 0
        ;;
      *)
        if entry="$(entry_by_name "$1")"; then
          selected+=("$entry")
        else
          echo "unknown capture name: $1" >&2
          echo "known names:" >&2
          for entry in "${entries[@]}"; do
            IFS=: read -r stem source host output <<<"$entry"
            printf '  %s (%s -> %s)\n' "$stem" "$source" "$output" >&2
          done
          exit 2
        fi
        ;;
    esac
    shift
  done
fi

require_file "$cart_rom" "Action! cartridge ROM"
require_file "$os_rom" "Atari OS ROM"
require_file "$vm_root/Cargo.toml" "action-compiler-vm project"
mkdir -p "$out_dir"

host_file_args=()
while IFS= read -r sidecar; do
  name="$(basename "$sidecar" .atascii | tr '[:lower:]' '[:upper:]')"
  host_file_args+=(--host-file "$name:$sidecar")
done < <(find "$toolkit_dir" -maxdepth 1 -type f -name '*.atascii' | sort)

tmp_root="$(mktemp -d "${TMPDIR:-/tmp}/actionc-toolkit-original-demos.XXXXXX")"
trap 'rm -rf "$tmp_root"' EXIT

summary="$out_dir/TOOLKIT_DEMOS_ORIGINAL.md"
{
  echo "# Toolkit Original Demo Captures"
  echo
  echo "Generated by \`surveys/toolkit/capture-original-demos.sh\`."
  echo
  echo "Raw \`*.atascii\` sidecars are compiled with the original Action! compiler VM."
  echo "Each temporary source is prefixed with \`SET \$491=\$3000\` and \`SET \$E=\$3000\`."
  echo "A source can still override that origin itself; \`KALSCOPE.DEM\` intentionally resets it to \`$5000\`."
  echo
  echo "| Stem | Source | Object | Status | Size | Code Segment | RUNAD |"
  echo "| --- | --- | --- | --- | ---: | --- | --- |"
} > "$summary"

for entry in "${selected[@]}"; do
  IFS=: read -r stem source host_source output_name <<<"$entry"
  source_sidecar="$toolkit_dir/$source.atascii"
  source_text="$toolkit_dir/$source"
  main_source="$tmp_root/$host_source"
  source_copy="$out_dir/$stem.source.atascii"
  output_path="$out_dir/$output_name"
  symbols_path="$out_dir/$stem.symbols.json"
  snapshots_path="$out_dir/$stem.symbol-snapshots.json"
  log_path="$out_dir/$stem.capture.log"
  info_path="$out_dir/$stem.load-info.txt"
  compare_path="$out_dir/$stem.compare.txt"

  require_file "$source_sidecar" "$source raw source sidecar"
  require_file "$source_text" "$source decoded source"

  rm -f "$main_source" "$source_copy" "$output_path" "$symbols_path" \
    "$snapshots_path" "$log_path" "$info_path" "$compare_path"
  printf 'SET $491=$3000\233SET $E=$3000\233' > "$main_source"
  cat "$source_sidecar" >> "$main_source"
  cp "$main_source" "$source_copy"

  printf -v monitor_input 'C "H:%s"\nW "H:%s"\n' "$host_source" "$output_name"
  echo "==> $source -> $output_name"
  if (
    cd "$vm_root"
    cargo run --quiet -- run \
      --cart "$cart_rom" \
      --os "$os_rom" \
      --hotpatch action-q-input \
      --hotpatch action-headless-getkey \
      --host-file "$host_source:$main_source" \
      "${host_file_args[@]}" \
      --host-output "$output_name:$output_path" \
      --dump-symbols-on-stop "$symbols_path" \
      --dump-symbol-snapshots-on-stop "$snapshots_path" \
      --action-symbol-hooks \
      --monitor-key-at-pc '$A2E0' \
      --q-input-at-pc-after '$A2E0:$B2F5:'"$monitor_input" \
      --max-steps "$max_steps" \
      --history 20
  ) >"$log_path" 2>&1; then
    vm_status="vm-ok"
  else
    vm_status="vm-failed"
  fi
  sanitize_capture_log "$log_path"

  if [[ -s "$output_path" ]]; then
    size="$(wc -c < "$output_path" | tr -d ' ')"
    (
      cd "$repo_root"
      cargo run --quiet --bin atari-load-info -- "$output_path"
    ) > "$info_path" 2>&1 || true

    if (
      cd "$repo_root"
      cargo run --quiet --bin actionc-compare -- \
        --origin '$3000' \
        --original "$output_path" \
        --original-symbols "$symbols_path" \
        --original-symbol-snapshots "$snapshots_path" \
        --disassemble-original \
        --max-diffs 24 \
        --mode compat \
        "$source_text"
    ) > "$compare_path" 2>&1; then
      compare_status="compare-ok"
    else
      compare_status="compare-failed"
    fi

    code_segment="$(awk '/^seg 00:/ { print $3; exit }' "$info_path")"
    runad="$(awk '/RUNAD/ { print $4; exit }' "$info_path")"
    printf '| `%s` | `%s` | `%s` | %s/%s | %s | `%s` | `%s` |\n' \
      "$stem" "$source" "$output_name" "$vm_status" "$compare_status" \
      "$size" "${code_segment:-?}" "${runad:-?}" >> "$summary"
  else
    printf '| `%s` | `%s` | `%s` | %s | 0 | - | - |\n' \
      "$stem" "$source" "$output_name" "$vm_status" >> "$summary"
    echo "FAILED: $output_path was not written or is empty; see $log_path" >&2
  fi
done

cat "$summary"
