#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: surveys/toolkit/survey.sh [--output <report.md>] [--toolkit-dir <dir>] [--modern-dir <dir>]

Survey the extracted official ACTION! Toolkit sources with the current actionc.
The report checks each selected source across the supported profile/backend
combinations:

  legacy + classic
  modern + classic
  modern + mir6502

Each row is classified by the furthest stage reached:

  lex      tokenization succeeds
  check    parse + semantic analysis succeeds
  codegen  code generation succeeds

Modernized source overlays are read from samples/toolkit/modern by default.
When an overlay file exists, the survey compiles through a temporary Toolkit
directory containing the original extracted files plus that overlay, so demo
INCLUDE directives still resolve against the Toolkit library files.

USAGE
}

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/../.." && pwd)"
toolkit_dir="$repo_root/corpora/toolkit/original/extracted"
modern_dir="$repo_root/samples/toolkit/modern"
report="$script_dir/TOOLKIT_SURVEY.md"

first_error() {
  local file="$1"
  local line
  line="$(sed -n '/[^[:space:]]/ { s/[[:space:]]\+/ /g; p; q; }' "$file")"
  if [ -z "$line" ]; then
    line="command failed without diagnostics"
  fi
  if [ -n "${tmp_dir:-}" ]; then
    line="${line//"$tmp_dir"/[tmp]}"
  fi
  printf '%s' "$line"
}

escape_md() {
  local text="$1"
  text="${text//\\/\\\\}"
  text="${text//|/\\|}"
  printf '%s' "$text"
}

display_path() {
  local path="$1"
  case "$path" in
    "$repo_root"/*) printf '%s' "${path#"$repo_root"/}" ;;
    *) printf '%s' "$path" ;;
  esac
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --output)
      shift
      if [ "$#" -eq 0 ]; then
        echo "--output requires a path" >&2
        exit 2
      fi
      report="$1"
      ;;
    --toolkit-dir)
      shift
      if [ "$#" -eq 0 ]; then
        echo "--toolkit-dir requires a path" >&2
        exit 2
      fi
      toolkit_dir="$1"
      ;;
    --modern-dir)
      shift
      if [ "$#" -eq 0 ]; then
        echo "--modern-dir requires a path" >&2
        exit 2
      fi
      modern_dir="$1"
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

if [ ! -d "$toolkit_dir" ]; then
  echo "missing toolkit directory: $toolkit_dir" >&2
  exit 1
fi

cd "$repo_root"
cargo build --quiet
actionc="$repo_root/target/debug/actionc-emit"

tmp_dir="$(mktemp -d "${TMPDIR:-/tmp}/actionc-toolkit-survey.XXXXXX")"
trap 'rm -rf "$tmp_dir"' EXIT

overlaid_toolkit_dir="$tmp_dir/toolkit"
mkdir -p "$overlaid_toolkit_dir"
while IFS= read -r toolkit_file; do
  ln -s "$toolkit_file" "$overlaid_toolkit_dir/$(basename "$toolkit_file")"
done < <(find "$toolkit_dir" -maxdepth 1 -type f | sort)

if [ -d "$modern_dir" ]; then
  while IFS= read -r overlay_file; do
    rm -f "$overlaid_toolkit_dir/$(basename "$overlay_file")"
    ln -s "$overlay_file" "$overlaid_toolkit_dir/$(basename "$overlay_file")"
  done < <(find "$modern_dir" -maxdepth 1 -type f ! -name '.*' | sort)
fi

compat_original_dir="$tmp_dir/original/extracted"
mkdir -p "$compat_original_dir"
while IFS= read -r toolkit_file; do
  ln -s "$toolkit_file" "$compat_original_dir/$(basename "$toolkit_file")"
done < <(find "$overlaid_toolkit_dir" -maxdepth 1 \( -type f -o -type l \) | sort)

sources=()
while IFS= read -r source_name; do
  sources+=("$source_name")
done < <(
  {
    find "$toolkit_dir" -maxdepth 1 -type f \( -name '*.ACT' -o -name '*.DEM' -o -name '*.DM1' -o -name '*.DM2' \) -exec basename {} \;
    if [ -d "$modern_dir" ]; then
      find "$modern_dir" -maxdepth 1 -type f ! -name '.*' \( -name '*.ACT' -o -name '*.DEM' -o -name '*.DM1' -o -name '*.DM2' \) -exec basename {} \;
    fi
  } | sort -u
)

config_profiles=(legacy modern modern)
config_backends=(classic classic mir6502)

{
  echo "# ACTION! Toolkit Survey"
  echo
  echo "Generated by \`surveys/toolkit/survey.sh\`."
  echo
  echo "Toolkit directory: \`$(display_path "$toolkit_dir")\`"
  echo "Modern overlay directory: \`$(display_path "$modern_dir")\`"
  echo
  echo "Survey policy:"
  echo
  echo "- Checked extensions: \`.ACT\`, \`.DEM\`, \`.DM1\`, \`.DM2\`."
  echo "- Modernized files under \`$(display_path "$modern_dir")\` overlay the extracted Toolkit files without modifying \`$(display_path "$toolkit_dir")\`."
  echo "- Demo sources compile through the overlaid Toolkit directory so local and Atari-device \`INCLUDE\` directives resolve against the surveyed library files."
  echo "- Every checked source is compiled with the supported profile/backend combinations."
  echo "- \`legacy\` + \`mir6502\` is skipped because the MIR6502 backend only supports the modern profile."
  echo
  echo "| Source | Actual Source | Profile | Backend | Status | Detail |"
  echo "| --- | --- | --- | --- | --- | --- |"
} > "$report"

configs=0
lex_ok=0
check_ok=0
codegen_ok=0
failures=0

for name in "${sources[@]}"; do
  src="$toolkit_dir/$name"
  actual_source="$src"
  compile_src="$overlaid_toolkit_dir/$name"

  if [ -f "$modern_dir/$name" ]; then
    actual_source="$modern_dir/$name"
  fi

  case "$name" in
    ALLOCATE.ACT)
      if [ "$actual_source" = "$src" ]; then
        compile_src="$overlaid_toolkit_dir/__ALLOCATE_HARNESS.ACT"
        {
          echo "CARD EndProg"
          echo "INCLUDE \"ALLOCATE.ACT\""
        } > "$compile_src"
        detail="emits compatible code with required EndProg harness"
      fi
      ;;
  esac

  for config_index in "${!config_profiles[@]}"; do
    profile="${config_profiles[$config_index]}"
    backend="${config_backends[$config_index]}"
    configs=$((configs + 1))
    err="$tmp_dir/$name.$profile.$backend.err"
    status="codegen-ok"
    detail="emits code"

    if ! "$actionc" --profile "$profile" --backend "$backend" --emit-tokens "$compile_src" >/dev/null 2>"$err"; then
      status="lex-blocked"
      detail="$(first_error "$err")"
      failures=$((failures + 1))
    else
      lex_ok=$((lex_ok + 1))
      if ! "$actionc" --profile "$profile" --backend "$backend" "$compile_src" >/dev/null 2>"$err"; then
        status="check-blocked"
        detail="$(first_error "$err")"
        failures=$((failures + 1))
      else
        check_ok=$((check_ok + 1))
        if ! "$actionc" --profile "$profile" --backend "$backend" --emit-code "$compile_src" >/dev/null 2>"$err"; then
          status="codegen-blocked"
          detail="$(first_error "$err")"
          failures=$((failures + 1))
        else
          codegen_ok=$((codegen_ok + 1))
        fi
      fi
    fi

    printf '| `%s` | `%s` | `%s` | `%s` | %s | %s |\n' \
      "$name" "$(escape_md "$(display_path "$actual_source")")" "$profile" "$backend" "$status" "$(escape_md "$detail")" >> "$report"
  done
done

{
  echo
  echo "Summary:"
  echo
  echo "- Sources tracked: ${#sources[@]}"
  echo "- Profile/backend configurations: $configs"
  echo "- Tokenize: $lex_ok"
  echo "- Parse + semantic check: $check_ok"
  echo "- Codegen: $codegen_ok"
  echo "- Not yet supported: $failures"
} >> "$report"

cat "$report"
