#!/usr/bin/env python3
"""Keep the hosted interface and native provider contract together."""
import argparse
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]

def interface(contract):
    lines=['; Generated by tools/generate_cstring.py; do not edit.',
           '; Use CSTRING.IMPL for standalone source inclusion.', 'MODULE CSTRING']
    for name,spec in contract['providers'].items():
        args=' '.join(kind+' '+name for kind,name in spec['arguments'])
        lines.append(f'PUBLIC EXTERNAL {spec["result"]} FUNC {name}({args})')
    return '\n'.join(lines+['ENDMODULE',''])

if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    contract=json.loads((ROOT/'embedded/modules/cstring/contract.json').read_text())
    path=ROOT/'embedded/modules/cstring.act'
    text=interface(contract)
    if args.check:
        if path.read_text()!=text: raise SystemExit('CSTRING interface is stale')
    else: path.write_text(text)
