#!/usr/bin/env python3
"""Generate the native 65816 ABI constants. No third-party dependencies."""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "docs/abi/action65816-native-v1.json"
RUST = ROOT / "src/mir65816/abi/generated.rs"
ASSEMBLY = ROOT / "docs/abi/action65816-native-v1.inc"


def constants(spec):
    values = [("ABI_VERSION", "/abi_version", spec["abi_version"])]

    def number(name, path, value):
        if type(value) is not int or not 0 <= value <= 0xFFFFFFFF:
            raise ValueError(f"{path}: expected an unsigned 32-bit constant")
        values.append((name, path, value))

    for section, prefix in [
        ("boundary", "BOUNDARY"),
        ("calls", "CALL"),
        ("frames", "FRAME"),
        ("direct_page", "DP"),
        ("saved_frame", "SAVED_FRAME"),
        ("context_record", "CONTEXT_RECORD"),
        ("interrupts", "INTERRUPT"),
        ("first_task", "FIRST_TASK"),
    ]:
        for key, value in spec[section].items():
            if type(value) is int:
                number(f"{prefix}_{key.upper()}", f"/{section}/{key}", value)
        for index, field in enumerate(spec[section].get("fields", [])):
            for key in ["offset", "size"]:
                number(f"{prefix}_{field['name'].upper()}_{key.upper()}",
                       f"/{section}/fields/{index}/{key}", field[key])
    for name, scalar in spec["scalar_classes"].items():
        for key in ["size", "alignment"]:
            number(f"SCALAR_{name.upper()}_{key.upper()}",
                   f"/scalar_classes/{name}/{key}", scalar[key])
    for section, key, prefix in [
        ("direct_page", "domain_kinds", "DOMAIN"),
        ("interrupts", "dispatch_reasons", "DISPATCH"),
    ]:
        for name, value in spec[section][key].items():
            number(f"{prefix}_{name.upper()}", f"/{section}/{key}/{name}", value)
    for index, alias in enumerate(spec["direct_page"]["scratch_aliases"]):
        for key in ["offset", "size"]:
            number(f"DP_{alias['name'].upper()}_{key.upper()}",
                   f"/direct_page/scratch_aliases/{index}/{key}", alias[key])
    for name, value in spec["irq_state_tokens"].items():
        number(f"IRQ_TOKEN_{name.upper()}", f"/irq_state_tokens/{name}", value)
    assert len({name for name, _, _ in values}) == len(values)
    return values


def render(raw):
    spec = json.loads(raw)
    values = constants(spec)
    # Normalize host line endings before fingerprinting; this is not image data.
    fingerprint = 0xCBF29CE484222325
    for byte in raw.replace("\r\n", "\n").encode():
        fingerprint = ((fingerprint ^ byte) * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    rust = ["// Generated by tools/generate_abi65816.py; do not edit.",
            f'pub const ABI_NAME: &str = {json.dumps(spec["abi"])};',
            f"pub const MANIFEST_FINGERPRINT: u64 = 0x{fingerprint:016x};"]
    assembly = ["; Generated by tools/generate_abi65816.py; do not edit.",
                f'; ABI: {spec["abi"]}']
    for name, _, value in values:
        rust.append(f"pub const {name}: u32 = {value};")
        assembly.append(f"A816_{name} = ${value:04X}")
    rust.extend(["", "#[cfg(test)]", "#[rustfmt::skip]", "pub(super) const MANIFEST_VALUES: &[(&str, &str, u32)] = &["])
    rust.extend(f'    ("{path}", "A816_{name}", {name}),' for name, path, _ in values)
    rust.append("];")
    return "\n".join(rust) + "\n", "\n".join(assembly) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="check committed generated files")
    args = parser.parse_args()
    outputs = render(MANIFEST.read_text(encoding="utf-8"))
    stale = []
    for path, output in zip([RUST, ASSEMBLY], outputs):
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != output:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(output, encoding="utf-8", newline="\n")
    if stale:
        parser.exit(1, "Stale ABI constants: " + ", ".join(stale) + "\n")


if __name__ == "__main__":
    main()
