mod analysis;

pub mod asm6502;
pub mod ast;
pub mod build_info;
pub mod cli;
pub mod codegen;
pub mod compiler;
pub mod diagnostic;
pub mod embedded_vfs;
pub mod includes;
pub mod lexer;
pub mod map_query;
pub mod mir6502;
pub mod nir;
pub mod parser;
pub mod resident;
pub mod runner;
pub mod runtime;
pub(crate) mod runtime_bindings;
pub(crate) mod runtime_source;
pub mod semantic;
pub mod source;
