#!/usr/bin/env python3
"""Generate both runtime tables directly from the pinned CP1919 CSV."""

import argparse
import csv
import hashlib
import math
from pathlib import Path


EXPECTED_SHA256 = "77b3c342840c7b63286303a7bbeec399862b9684b25eafb638d57095ac30c400"
SOURCE_URL = (
    "https://raw.githubusercontent.com/pachadotdev/cp1919/"
    "ede09bbbdf6f8d7f88ea8c530866bf6cdb3064b1/cp1919.csv"
)
TRACE_COUNT = 80
VISIBLE_TRACES = 50
SAMPLES_PER_TRACE = 300
SCALE = 0.625
BIAS = 4


def read_source(path: Path) -> list[list[float]]:
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    if digest != EXPECTED_SHA256:
        raise SystemExit(
            f"unexpected source SHA-256 {digest}; expected {EXPECTED_SHA256}"
        )

    traces = [[] for _ in range(TRACE_COUNT)]
    with path.open(newline="", encoding="utf-8") as stream:
        reader = csv.DictReader(stream)
        if reader.fieldnames != ["x", "y", "z"]:
            raise SystemExit(f"unexpected CSV columns: {reader.fieldnames!r}")
        for row in reader:
            trace = int(row["y"])
            if not 1 <= trace <= TRACE_COUNT:
                raise SystemExit(f"trace number out of range: {trace}")
            if int(row["x"]) != len(traces[trace - 1]) + 1:
                raise SystemExit(f"trace {trace}: samples are out of order")
            traces[trace - 1].append(float(row["z"]))
    if {len(trace) for trace in traces} != {SAMPLES_PER_TRACE}:
        raise SystemExit("expected 80 traces of 300 source measurements")
    return traces


def encode(trace: list[float], fraction_bits: int) -> list[int]:
    unit = 1 << fraction_bits
    encoded = []
    for value in trace:
        value *= SCALE * unit
        # Round nearest, with ties away from zero, before adding the byte bias.
        height = math.ceil(value - 0.5) if value < 0 else math.floor(value + 0.5)
        height = max(-4 * unit, min(47 * unit, height))
        encoded.append(height + BIAS * unit)
    return encoded


def render_table(heights: list[int], vbxe: bool) -> str:
    lines = [
        "; Generated by generate-data.py from the pinned CP1919 CSV.",
        "; Source: CP1919 pulse-profile dataset published by pachadotdev:",
        f"; {SOURCE_URL}",
        f"; Source SHA-256: {EXPECTED_SHA256}",
        "; The source repository applies CC0-1.0 to the dataset, but notes that",
        "; its earlier provenance is unknown. Treat this as a digitization of",
        "; Harold Craft's plot rather than verified raw Arecibo samples.",
        "; Heights use a vertical scale of 0.625 before rounding.",
    ]
    if vbxe:
        lines += [
            "; All 80 traces retain all 300 horizontal samples for VBXE SR320.",
            "; Quarter-scanline heights have a stored bias of 16.",
            "",
            "BYTE ARRAY pulseData(PULSE_DATA_SIZE)=[",
        ]
    else:
        lines += [
            "; 50 evenly spaced traces retain all 300 horizontal samples.",
            "; Integer heights have a stored bias of 4 for Graphics 8.",
            "",
            "BYTE ARRAY pulseData(15000)=[",
        ]
    columns = 16 if vbxe else 15
    for offset in range(0, len(heights), columns):
        row = heights[offset:offset + columns]
        values = [f"${value:02X}" if vbxe else str(value) for value in row]
        lines.append("  " + " ".join(values))
    lines[-1] += "]"
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path, help="the pinned cp1919.csv")
    parser.add_argument("--check", action="store_true", help="verify tables without writing")
    args = parser.parse_args()
    traces = read_source(args.source)

    # Select 50 evenly spaced traces before encoding integer heights. Encoding
    # the original CSV avoids rounding the quarter-scanline VBXE values twice.
    selected = []
    for n in range(VISIBLE_TRACES):
        trace = (n * TRACE_COUNT + VISIBLE_TRACES - 1) // VISIBLE_TRACES
        selected.extend(encode(traces[trace], fraction_bits=0))
    for index, height in enumerate(selected):
        baseline = 181 - (index // SAMPLES_PER_TRACE) * 3
        if not 0 <= baseline + BIAS - height < 192:
            raise SystemExit("pulse height exceeds the Graphics 8 screen")
    vbxe = [height for trace in traces for height in encode(trace, fraction_bits=2)]

    project = Path(__file__).resolve().parent
    for name, contents in [
        ("UPDATA.ACT", render_table(selected, vbxe=False)),
        ("unknown-pleasures-vbxe-data.inc", render_table(vbxe, vbxe=True)),
    ]:
        path = project / name
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != contents:
                raise SystemExit(f"stale generated table: {path}")
            print(f"verified {name}")
        else:
            path.write_text(contents, encoding="utf-8")
            print(f"wrote {name}")


if __name__ == "__main__":
    main()
